#!/usr/bin/env python3
"""make_pnr_inputs.py - derive the nextpnr-xilinx inputs from the beta XDC (read-only on beta/fpga).

Writes
  pnr/radar_system_top_beta_pnr.xdc  only PACKAGE_PIN / IOSTANDARD of constrained ports and the
                                      create_clock lines (nextpnr-xilinx xdc.cc parses set_property,
                                      create_clock and set_multicycle_path only)
  build/pnr_unconstrained.ys          `delete -port` for every top-level port without PACKAGE_PIN
                                      (the 116 UNRESOLVED bits: ft601_*, dbg_*, current_*, ...); they
                                      become internal nets so the design fits the 170 user I/O of
                                      the FTG256 package. Inputs among them are left undriven.
Usage: python3 make_pnr_inputs.py <xdc> <top.v>     Exit: 0 ok, 1 error. Stdlib only.
"""
import re, sys, os
HERE = os.path.dirname(os.path.abspath(__file__))
def main(xdc, top):
    src = open(xdc).read().splitlines()
    out, pinned = [], set()
    for ln in src:
        code = ln.split(';#')[0].strip()
        m = re.match(r'set_property\s+(PACKAGE_PIN|IOSTANDARD)\s+(\S+)\s+\[get_ports\s+(?:\{([^}]+)\}|([^\]\s]+))\s*\]', code)
        if m:
            port = (m.group(3) or m.group(4)).strip()
            out.append(f"set_property {m.group(1)} {m.group(2)} [get_ports {{{port}}}]")
            if m.group(1) == 'PACKAGE_PIN': pinned.add(port)
        elif code.startswith('create_clock'):
            out.append(code)
    # ports of the top module
    t = open(top).read()
    hdr = t[t.index('module radar_system_top'):]
    hdr = hdr[:hdr.index(');')]
    hdr = re.sub(r'//[^\n]*', '', hdr)
    ports = []
    for m in re.finditer(r'\b(input|output|inout)\s+(?:wire|reg)?\s*(\[(\d+):(\d+)\])?\s*([^;]*?)(?=\b(?:input|output|inout)\b|$)', hdr, re.S):
        names = [n.strip() for n in m.group(5).replace('\n', ' ').split(',') if n.strip()]
        for n in names:
            if m.group(2):
                hi, lo = int(m.group(3)), int(m.group(4))
                ports.append((n, [f"{n}[{i}]" for i in range(lo, hi + 1)]))
            else:
                ports.append((n, [n]))
    uncon, nbits = [], 0
    for name, bits in ports:
        miss = [b for b in bits if b not in pinned]
        if miss and len(miss) != len(bits):
            print(f"ERROR: port {name} partly constrained", file=sys.stderr); return 1
        if miss: uncon.append(name); nbits += len(bits)
    # create_clock on a port that is removed must be dropped
    out = [l for l in out if not any(f"get_ports {u}]" in l or f"get_ports {{{u}}}]" in l for u in uncon)]
    os.makedirs(os.path.join(HERE, 'pnr'), exist_ok=True); os.makedirs(os.path.join(HERE, 'build'), exist_ok=True)
    with open(os.path.join(HERE, 'pnr', 'radar_system_top_beta_pnr.xdc'), 'w') as f:
        f.write("# generated by make_pnr_inputs.py from beta/fpga/constraints/radar_system_top_beta.xdc\n")
        f.write("# PACKAGE_PIN/IOSTANDARD + create_clock only (nextpnr-xilinx subset). NOT a Vivado constraint file.\n")
        f.write("\n".join(out) + "\n")
    with open(os.path.join(HERE, 'build', 'pnr_unconstrained.ys'), 'w') as f:
        f.write("# generated by make_pnr_inputs.py: top-level ports without PACKAGE_PIN -> internal nets\n")
        for u in uncon: f.write(f"delete -port radar_system_top/{u}\n")
    print(f"ports: {len(ports)} ({sum(len(b) for _, b in ports)} bits); pinned bits: {len(pinned)}; "
          f"unconstrained ports demoted: {len(uncon)} ({nbits} bits): {' '.join(uncon)}")
    return 0
if __name__ == '__main__':
    sys.exit(main(sys.argv[1], sys.argv[2]))
