"""Replay helpers: raw FPGA byte captures and the testbench CSV.

``load_testbench_csv`` reads ``9_Firmware/9_3_GUI/test_radar_data.csv``
(columns ``timestamp_ns,chirp_number,chirp_type,sample_index,I_value,Q_value,
magnitude_squared``; generated by ``8_Utils/Python/CSV_radar.py``) into
per-chirp complex sample arrays, as ``GUI_V4_2_CSV.py`` did with pandas.
pandas is not required here.
"""
from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterator, Tuple

import numpy as np


def load_testbench_csv(path: str | Path) -> Dict[Tuple[str, int], np.ndarray]:
    """Return ``{(chirp_type, chirp_number): complex ndarray ordered by sample_index}``."""
    groups: Dict[Tuple[str, int], list] = defaultdict(list)
    with open(path, newline="") as fh:
        reader = csv.DictReader(fh)
        required = {"chirp_number", "chirp_type", "sample_index", "I_value", "Q_value"}
        if not required.issubset(reader.fieldnames or ()):
            raise ValueError(f"CSV lacks columns {sorted(required - set(reader.fieldnames or ()))}")
        for row in reader:
            key = (row["chirp_type"], int(row["chirp_number"]))
            groups[key].append((int(row["sample_index"]), float(row["I_value"]), float(row["Q_value"])))
    out = {}
    for key, rows in groups.items():
        rows.sort()
        out[key] = np.array([i for _, i, _ in rows]) + 1j * np.array([q for _, _, q in rows])
    return out


def iter_capture(path: str | Path, chunk: int = 4096) -> Iterator[bytes]:
    """Yield a raw byte capture (e.g. from an RTL simulation dump) in chunks."""
    with open(path, "rb") as fh:
        while True:
            data = fh.read(chunk)
            if not data:
                return
            yield data
