# ============================================================================
# radar_system_top_beta.xdc  -  AERIS-10 beta FPGA constraints (XC7A50T-2FTG256I)
# STATUS: BETA - NOT RUN THROUGH VIVADO, NOT VERIFIED ON HARDWARE.
#
# Sources
#   * pin assignments: 9_Firmware/9_2_FPGA/reconstructed/radar_system_top_schematic_derived.xdc
#     (schematic part U42, generated by tools/gen_xdc_from_schematic.py); every PACKAGE_PIN
#     must be cross-checked against the AMD FTG256 package file before use
#   * clock periods: 9_Firmware/9_2_FPGA/cntrt.xdc:14-27 and the AD9523 programming in the
#     STM32 firmware (OUT6 = 100 MHz, OUT11 = 120 MHz, OUT4/ADC = 400 MHz)
#   * AD9484 timing: datasheet "Output (LVDS-SDR)": tSKEW data-to-DCO = +/-0.07 ns
#   * bank voltages: schematic (bank 14/15 = +3V3_FPGA, bank 34 = +1V8_FPGA)
# Timing constraints are kept in this file together with the pins (single file for the
# beta project); vivado/create_project.tcl adds only this XDC.
# ============================================================================

# ---------------------------------------------------------------- clocks ----
create_clock -name clk_100m     -period 10.000 [get_ports clk_100m]       ;# AD9523 OUT6 "FPGA_SYSTEM_CLOCK"
create_clock -name clk_120m_dac -period  8.333 [get_ports clk_120m_dac]   ;# AD9523 OUT11 "FPGA_DAC"
create_clock -name adc_dco      -period  2.500 [get_ports adc_dco_p]      ;# AD9484 DCO, 400 MHz SDR
# ft601_clk_in has no board pin (FT601 not wired) and is not used by the beta RTL; the
# constraint is kept so that a future FT601 interface starts with a defined clock:
create_clock -name ft601_clk_in -period 10.000 [get_ports ft601_clk_in]
# Host-link option B: the STM32 SPI1 clock is a clock for host_bridge_spi (SCLK-domain slave,
# <= 27 MHz per option_b_signal_map.csv) and at the same time data for the ADAR1000 pass-through
# synchroniser (level_shifter_interface samples it with clk_100m) - Vivado reports the latter as
# a clock used as data, which is intended.
create_clock -name spi_sclk     -period 37.000 [get_ports stm32_sclk_3v3]   ;# 27 MHz max (STM32 SPI1, APB2 108 MHz / 4)
set_input_jitter [get_clocks clk_100m]     0.100
set_input_jitter [get_clocks clk_120m_dac] 0.100
set_input_jitter [get_clocks adc_dco]      0.050

# The four clocks come from different AD9523 outputs / devices with no phase relation
# the design relies on; every crossing is a synchroniser, a reset synchroniser or
# async_fifo (Gray pointers).
set_clock_groups -asynchronous \
    -group [get_clocks clk_100m] \
    -group [get_clocks clk_120m_dac] \
    -group [get_clocks adc_dco] \
    -group [get_clocks ft601_clk_in] \
    -group [get_clocks spi_sclk]

# ----------------------------------------------------- I/O timing ---------
# AD9484 LVDS data (datasheet Table 4, "Output (LVDS-SDR)", re-checked 2026-10-09):
#   SDR, DCO at the sample rate, data valid on the rising DCO edge,
#   data-to-DCO skew tSKEW = -0.07 .. +0.07 ns  (tPD 0.85 ns, tCPD 0.6 ns typ.)
# ADC_CAPTURE_MODE = 1 (default): DCO -> BUFIO (I/O clock) + BUFR /4 (regional clock, auto-derived
# generated clock "clk_div"); data -> IDELAYE2 (VAR_LOAD, calibrated by adc_capture_calib) ->
# ISERDESE2 SDR 1:4. The IDELAY calibration centres the sampling point at run time, so the
# static analysis below documents the datasheet skew; board trace skew (layout not finished)
# MUST be added to these numbers when the Main Board layout exists.
set_input_delay -clock adc_dco -max  0.070 [get_ports {adc_d_p[*] adc_d_n[*]}]
set_input_delay -clock adc_dco -min -0.070 [get_ports {adc_d_p[*] adc_d_n[*]}]
# ADC_CAPTURE_MODE = 0 (legacy, falling-edge IDDR capture) would additionally need:
# set_input_delay -clock adc_dco -max  0.070 [get_ports {adc_d_p[*] adc_d_n[*]}] -clock_fall -add_delay
# set_input_delay -clock adc_dco -min -0.070 [get_ports {adc_d_p[*] adc_d_n[*]}] -clock_fall -add_delay

# IDELAYCTRL reference: 200 MHz from the MMCM in clk_gen.v (auto-derived generated clock from
# clk_100m). Group every IDELAYE2 with its IDELAYCTRL (all in bank 14 / one clock region):
set_property -quiet IODELAY_GROUP adc_idelay_grp [get_cells -hier -filter {NAME =~ *u_idelayctrl*}]
set_property -quiet IODELAY_GROUP adc_idelay_grp [get_cells -hier -filter {NAME =~ *g_lane[*].u_idelay*}]
# BUFIO/BUFR: the DCO pins (N14/P14, IO_L12P/N_T1_MRCC_14) are a clock-capable pair in bank 14
# and all eight data pairs are in bank 14 (PIN_MAP_FROM_SCHEMATIC.md lines 27-42), so the BUFIO
# clock reaches every ISERDESE2 without crossing a clock region. The BUFR output and the MMCM
# output are generated clocks derived automatically; no create_generated_clock is needed.
# Check after implementation: report_clock_interaction (clk_div <-> clk_100m must be
# "asynchronous"/FIFO-crossed only), report_timing_summary on clk_div and clk_200m paths.

# AD9708 DAC data (dac_data[7:0]) is clocked by the DAC's own clock from AD9523 OUT10
# (no FPGA pin, see UNRESOLVED dac_clk); set_output_delay values need the AD9708
# setup/hold figures relative to that clock and the board skew - UNRESOLVED, placeholder:
# set_output_delay -clock clk_120m_dac -max 2.0 [get_ports {dac_data[*]}]
# set_output_delay -clock clk_120m_dac -min -0.5 [get_ports {dac_data[*]}]

# Asynchronous STM32 lines (synchronised inside: edge_detector_enhanced, reset synchronisers)
set_false_path -from [get_ports {stm32_new_chirp stm32_new_elevation stm32_new_azimuth stm32_mixers_enable reset_n}]
# ADAR1000 SPI pass-through is re-timed by clk_100m flops: the 3.3 V inputs are asynchronous
# to clk_100m (false paths limited to the level-shifter cells, -quiet in case of renaming).
set_false_path -quiet -from [get_ports {stm32_sclk_3v3 stm32_mosi_3v3 stm32_cs_adar*_3v3 stm32_miso_1v8 spi_bridge_cs_n}] \
                      -to [get_cells -hier -filter {NAME =~ *ls_adar*}]
set_false_path -to   [get_ports {stm32_sclk_1v8 stm32_mosi_1v8 stm32_cs_adar*_1v8}]
# Bridge (spi_sclk domain): MOSI is sampled on the rising SCLK edge, MISO changes on the falling
# edge (mode 0). STM32F7 SPI1 master timing versus SCLK at the FPGA pins is UNRESOLVED (needs the
# STM32 datasheet tv/tsu figures and the board trace delays); placeholders, not active:
# set_input_delay  -clock spi_sclk -max 10.0 [get_ports {stm32_mosi_3v3 spi_bridge_cs_n}]
# set_input_delay  -clock spi_sclk -min  0.0 [get_ports {stm32_mosi_3v3 spi_bridge_cs_n}]
# set_output_delay -clock spi_sclk -max  5.0 [get_ports stm32_miso_3v3]
set_false_path -to [get_ports {stm32_miso_3v3 spi_bridge_drdy spi_bridge_spare}]
set_false_path -to   [get_ports {adar_* tx_mixer_en rx_mixer_en fpga_rf_switch dac_sleep adc_pwdn}]

# Synchroniser cells: ASYNC_REG is set in the RTL; the max-delay below bounds the
# metastability settling path (optional; -quiet so a renamed hierarchy does not error)
set_false_path -quiet -to [get_cells -hier -regexp {.*(signal_sync0|_meta|sync_ff_reg\[0\]|rd_gray_wsync1|wr_gray_rsync1).*}]

# ------------------------------------------------- configuration ----------
# Bank 0 VCCO = +3V3_FPGA on the schematic (CFGBVS pull direction via R to be verified)
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLDOWN [current_design]

# --------------------------------------------------- pin assignments -------
# Verbatim from the schematic-derived file, with these edits:
#  * adc_d_*/adc_dco_*: bank 14 is 3.3 V on the schematic. LVDS_25 inputs in a 3.3 V HR
#    bank are allowed only with DIFF_TERM = FALSE and an external 100 Ohm termination
#    (UG471). This is a DESIGN CONFLICT to be resolved by the board designer:
#      option A (active below): LVDS_25 + DIFF_TERM FALSE, external termination required;
#      option B (commented):    change bank-14 VCCO to 2.5 V, then DIFF_TERM TRUE is legal
#                                (requires a PCB change: bank 14 also carries the QSPI flash
#                                and adc_pwdn at 3.3 V levels).


set_property PACKAGE_PIN E12 [get_ports {clk_100m}]   ;# net FPGA_SYS_CLOCK, pin IO_L13P_T2_MRCC_15 [MEDIUM]
set_property IOSTANDARD LVCMOS33 [get_ports {clk_100m}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN C13 [get_ports {clk_120m_dac}]   ;# net FPGA_DAC_CLOCK, pin IO_L12N_T1_MRCC_15 [MEDIUM]
set_property IOSTANDARD LVCMOS33 [get_ports {clk_120m_dac}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN N14 [get_ports {adc_dco_p}]   ;# net ADC_DCO_P, pin IO_L12P_T1_MRCC_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_dco_p}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_dco_p}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_dco_p}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN P14 [get_ports {adc_dco_n}]   ;# net ADC_DCO_N, pin IO_L12N_T1_MRCC_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_dco_n}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_dco_n}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_dco_n}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN T5 [get_ports {adc_pwdn}]   ;# net ADC_PWRD, pin IO_L23N_T3_A02_D18_14 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_pwdn}]   ;# bank 14 VCCO=+3V3_FPGA
set_property PACKAGE_PIN A15 [get_ports {dac_sleep}]   ;# net DAC_SLEEP, pin IO_L9N_T1_DQS_AD3N_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sleep}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN C11 [get_ports {tx_mixer_en}]   ;# net MIX_TX_EN, pin IO_L11P_T1_SRCC_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_mixer_en}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN D11 [get_ports {rx_mixer_en}]   ;# net MIX_RX_EN, pin IO_L14N_T2_SRCC_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {rx_mixer_en}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN G15 [get_ports {fpga_rf_switch}]   ;# net M3S_VCTRL, pin IO_L24N_T3_RS0_15 [MEDIUM]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_rf_switch}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN F13 [get_ports {stm32_new_chirp}]   ;# net DIG_0, pin IO_L16N_T2_A27_15 [MEDIUM]
set_property IOSTANDARD LVCMOS33 [get_ports {stm32_new_chirp}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN E16 [get_ports {stm32_new_elevation}]   ;# net DIG_1, pin IO_L17P_T2_A26_15 [MEDIUM]
set_property IOSTANDARD LVCMOS33 [get_ports {stm32_new_elevation}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN D16 [get_ports {stm32_new_azimuth}]   ;# net DIG_2, pin IO_L17N_T2_A25_15 [MEDIUM]
set_property IOSTANDARD LVCMOS33 [get_ports {stm32_new_azimuth}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN F15 [get_ports {stm32_mixers_enable}]   ;# net DIG_3, pin IO_L18P_T2_A24_15 [MEDIUM]
set_property IOSTANDARD LVCMOS33 [get_ports {stm32_mixers_enable}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN E15 [get_ports {reset_n}]   ;# net DIG_4, pin IO_L18N_T2_A23_15 [MEDIUM]
set_property IOSTANDARD LVCMOS33 [get_ports {reset_n}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN J16 [get_ports {stm32_sclk_3v3}]   ;# net STM32_SCLK1, pin IO_L23N_T3_FWE_B_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {stm32_sclk_3v3}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN H13 [get_ports {stm32_mosi_3v3}]   ;# net STM32_MOSI1, pin IO_L20N_T3_A19_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {stm32_mosi_3v3}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN G14 [get_ports {stm32_miso_3v3}]   ;# net STM32_MISO1, pin IO_L21P_T3_DQS_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {stm32_miso_3v3}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN P5 [get_ports {stm32_sclk_1v8}]   ;# net STM32_SCLK_1V8, pin IO_L10P_T1_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {stm32_sclk_1v8}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN M1 [get_ports {stm32_mosi_1v8}]   ;# net STM32_MOSI_1V8, pin IO_L2N_T0_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {stm32_mosi_1v8}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN N3 [get_ports {stm32_miso_1v8}]   ;# net STM32_MISO_1V8, pin IO_L3P_T0_DQS_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {stm32_miso_1v8}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN P15 [get_ports {adc_d_p[0]}]   ;# net ADC_D0_P, pin IO_L8P_T1_D11_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_p[0]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_p[0]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_p[0]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN R15 [get_ports {adc_d_p[1]}]   ;# net ADC_D1_P, pin IO_L9P_T1_DQS_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_p[1]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_p[1]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_p[1]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN T14 [get_ports {adc_d_p[2]}]   ;# net ADC_D2_P, pin IO_L10P_T1_D14_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_p[2]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_p[2]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_p[2]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN R13 [get_ports {adc_d_p[3]}]   ;# net ADC_D3_P, pin IO_L16P_T2_CSI_B_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_p[3]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_p[3]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_p[3]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN R10 [get_ports {adc_d_p[4]}]   ;# net ADC_D4_P, pin IO_L17P_T2_A14_D30_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_p[4]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_p[4]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_p[4]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN T9 [get_ports {adc_d_p[5]}]   ;# net ADC_D5_P, pin IO_L22P_T3_A05_D21_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_p[5]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_p[5]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_p[5]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN T7 [get_ports {adc_d_p[6]}]   ;# net ADC_D6_P, pin IO_L21P_T3_DQS_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_p[6]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_p[6]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_p[6]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN R6 [get_ports {adc_d_p[7]}]   ;# net ADC_D7_P, pin IO_L24P_T3_A01_D17_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_p[7]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_p[7]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_p[7]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN P16 [get_ports {adc_d_n[0]}]   ;# net ADC_D0_N, pin IO_L8N_T1_D12_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_n[0]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_n[0]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_n[0]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN R16 [get_ports {adc_d_n[1]}]   ;# net ADC_D1_N, pin IO_L9N_T1_DQS_D13_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_n[1]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_n[1]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_n[1]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN T15 [get_ports {adc_d_n[2]}]   ;# net ADC_D2_N, pin IO_L10N_T1_D15_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_n[2]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_n[2]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_n[2]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN T13 [get_ports {adc_d_n[3]}]   ;# net ADC_D3_N, pin IO_L16N_T2_A15_D31_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_n[3]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_n[3]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_n[3]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN R11 [get_ports {adc_d_n[4]}]   ;# net ADC_D4_N, pin IO_L17N_T2_A13_D29_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_n[4]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_n[4]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_n[4]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN T10 [get_ports {adc_d_n[5]}]   ;# net ADC_D5_N, pin IO_L22N_T3_A04_D20_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_n[5]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_n[5]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_n[5]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN T8 [get_ports {adc_d_n[6]}]   ;# net ADC_D6_N, pin IO_L21N_T3_DQS_A06_D22_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_n[6]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_n[6]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_n[6]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN R7 [get_ports {adc_d_n[7]}]   ;# net ADC_D7_N, pin IO_L24N_T3_A00_D16_14 [HIGH]
set_property IOSTANDARD LVDS_25 [get_ports {adc_d_n[7]}]   ;# option A - bank 14 VCCO=3.3V: external 100 Ohm termination REQUIRED (UG471) - REQUIRES VERIFICATION
set_property DIFF_TERM FALSE    [get_ports {adc_d_n[7]}]   ;# option A
# set_property DIFF_TERM TRUE   [get_ports {adc_d_n[7]}]   ;# option B - only if bank 14 VCCO is changed to 2.5 V (board change)
set_property PACKAGE_PIN A14 [get_ports {dac_data[0]}]   ;# net DAC_0, pin IO_L7N_T1_AD2N_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[0]}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN A13 [get_ports {dac_data[1]}]   ;# net DAC_1, pin IO_L7P_T1_AD2P_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[1]}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN A12 [get_ports {dac_data[2]}]   ;# net DAC_2, pin IO_L5N_T0_AD9N_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[2]}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN B11 [get_ports {dac_data[3]}]   ;# net DAC_3, pin IO_L4N_T0_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[3]}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN B10 [get_ports {dac_data[4]}]   ;# net DAC_4, pin IO_L4P_T0_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[4]}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN A10 [get_ports {dac_data[5]}]   ;# net DAC_5, pin IO_L3N_T0_DQS_AD1N_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[5]}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN A9 [get_ports {dac_data[6]}]   ;# net DAC_6, pin IO_L2N_T0_AD8N_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[6]}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN A8 [get_ports {dac_data[7]}]   ;# net DAC_7, pin IO_L2P_T0_AD8P_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[7]}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN F14 [get_ports {stm32_cs_adar1_3v3}]   ;# net ADAR_1_CS_3V3, pin IO_L21N_T3_DQS_A18_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {stm32_cs_adar1_3v3}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN H16 [get_ports {stm32_cs_adar2_3v3}]   ;# net ADAR_2_CS_3V3, pin IO_L22P_T3_A17_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {stm32_cs_adar2_3v3}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN G16 [get_ports {stm32_cs_adar3_3v3}]   ;# net ADAR_3_CS_3V3, pin IO_L22N_T3_A16_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {stm32_cs_adar3_3v3}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN J15 [get_ports {stm32_cs_adar4_3v3}]   ;# net ADAR_4_CS_3V3, pin IO_L23P_T3_FOE_B_15 [HIGH]
set_property IOSTANDARD LVCMOS33 [get_ports {stm32_cs_adar4_3v3}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN L5 [get_ports {stm32_cs_adar1_1v8}]   ;# net ADAR_1_CS_1V8, pin IO_0_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {stm32_cs_adar1_1v8}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN L4 [get_ports {stm32_cs_adar2_1v8}]   ;# net ADAR_2_CS_1V8, pin IO_L1P_T0_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {stm32_cs_adar2_1v8}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN M4 [get_ports {stm32_cs_adar3_1v8}]   ;# net ADAR_3_CS_1V8, pin IO_L1N_T0_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {stm32_cs_adar3_1v8}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN M2 [get_ports {stm32_cs_adar4_1v8}]   ;# net ADAR_4_CS_1V8, pin IO_L2P_T0_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {stm32_cs_adar4_1v8}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN P3 [get_ports {adar_tx_load_1}]   ;# net ADAR_TX_LOAD_1, pin IO_L5N_T0_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {adar_tx_load_1}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN T4 [get_ports {adar_tx_load_2}]   ;# net ADAR_TX_LOAD_2, pin IO_L9P_T1_DQS_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {adar_tx_load_2}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN R3 [get_ports {adar_tx_load_3}]   ;# net ADAR_TX_LOAD_3, pin IO_L8P_T1_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {adar_tx_load_3}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN R2 [get_ports {adar_tx_load_4}]   ;# net ADAR_TX_LOAD_4, pin IO_L7P_T1_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {adar_tx_load_4}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN M5 [get_ports {adar_rx_load_1}]   ;# net ADAR_RX_LOAD_1, pin IO_L6P_T0_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {adar_rx_load_1}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN T2 [get_ports {adar_rx_load_2}]   ;# net ADAR_RX_LOAD_2, pin IO_L8N_T1_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {adar_rx_load_2}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN R1 [get_ports {adar_rx_load_3}]   ;# net ADAR_RX_LOAD_3, pin IO_L7N_T1_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {adar_rx_load_3}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN N4 [get_ports {adar_rx_load_4}]   ;# net ADAR_RX_LOAD_4, pin IO_L6N_T0_VREF_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {adar_rx_load_4}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN N2 [get_ports {adar_tr_1}]   ;# net ADAR_TR_1, pin IO_L3N_T0_DQS_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {adar_tr_1}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN N1 [get_ports {adar_tr_2}]   ;# net ADAR_TR_2, pin IO_L4P_T0_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {adar_tr_2}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN P1 [get_ports {adar_tr_3}]   ;# net ADAR_TR_3, pin IO_L4N_T0_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {adar_tr_3}]   ;# bank 34 VCCO=+1V8_FPGA
set_property PACKAGE_PIN P4 [get_ports {adar_tr_4}]   ;# net ADAR_TR_4, pin IO_L5P_T0_34 [HIGH]
set_property IOSTANDARD LVCMOS18 [get_ports {adar_tr_4}]   ;# bank 34 VCCO=+1V8_FPGA

# ---- host-link option B (engineering/DESIGN/HOST_LINK/option_b_signal_map.csv) - nets exist on the board
set_property PACKAGE_PIN H11 [get_ports {spi_bridge_cs_n}]   ;# net DIG_5, pin IO_L19P_T3_A22_15, STM32 PD13 (firmware: becomes OUTPUT) [MEDIUM]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_bridge_cs_n}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PULLUP true [get_ports {spi_bridge_cs_n}]   ;# bridge inactive until the STM32 drives the line
set_property PACKAGE_PIN G12 [get_ports {spi_bridge_drdy}]   ;# net DIG_6, pin IO_L19N_T3_A21_VREF_15, STM32 PD14 (EXTI14) [MEDIUM]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_bridge_drdy}]   ;# bank 15 VCCO=+3V3_FPGA
set_property PACKAGE_PIN H12 [get_ports {spi_bridge_spare}]   ;# net DIG_7, pin IO_L20P_T3_A20_15, STM32 PD15 [MEDIUM]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_bridge_spare}]   ;# bank 15 VCCO=+3V3_FPGA

# ---------------- UNRESOLVED RTL PORTS (no schematic evidence) ----------------
# UNRESOLVED — REQUIRES BOARD DESIGN VERIFICATION: dac_clk
#     reason: RTL drives a DAC clock output, but the board clocks the AD9708 from AD9523 OUT10 (main.cpp:1019-1020); no FPGA net
# UNRESOLVED — REQUIRES BOARD DESIGN VERIFICATION: ft601_clk_in
#     reason: FT601Q-B-T (U6) is placed in the schematic but has 0 of 77 pins connected; its decoupling parts are parked outside the board outline
# UNRESOLVED — REQUIRES BOARD DESIGN VERIFICATION: ft601_data[*], ft601_be[*], ft601_txe_n, ft601_rxf_n, ft601_txe, ft601_rxf, ft601_wr_n, ft601_rd_n, ft601_oe_n, ft601_siwu_n, ft601_srb[*], ft601_swb[*], ft601_clk_out
#     reason: FT601 not wired on Main Board
# (DIG_5..DIG_7 are now used by the host-link option B ports above; the STM32 firmware must
#  reconfigure PD13 as an output - main.cpp:2313-2317 configures PD13..15 as inputs today)
# UNRESOLVED — REQUIRES BOARD DESIGN VERIFICATION: current_elevation[*], current_azimuth[*], current_chirp[*], new_chirp_frame
#     reason: no status outputs on the schematic
# UNRESOLVED — REQUIRES BOARD DESIGN VERIFICATION: dbg_doppler_data[*], dbg_doppler_valid, dbg_doppler_bin[*], dbg_range_bin[*], system_status[*]
#     reason: debug outputs; no schematic nets (internal-only in a real build; remove from top or leave unconstrained with -quiet)

# ---------------- schematic FPGA nets with NO RTL port ----------------
# ADC_OR_N               pad N6   pin IO_L19N_T3_A09_D25_VREF_14
# ADC_OR_P               pad M6   pin IO_L19P_T3_A10_D26_14
# FPGA_ADC_CLOCK_N       pad N12  pin IO_L13N_T2_MRCC_14
# FPGA_ADC_CLOCK_P       pad N11  pin IO_L13P_T2_MRCC_14
# FPGA_CLOCK_TEST        pad H14  pin IO_L24P_T3_RS1_15
# FPGA_FLASH_CLK         pad E8   pin CCLK_0
# FPGA_FLASH_DQ0         pad J13  pin IO_L1P_T0_D00_MOSI_14
# FPGA_FLASH_DQ1         pad J14  pin IO_L1N_T0_D01_DIN_14
# FPGA_FLASH_DQ2         pad K15  pin IO_L2P_T0_D02_14
# FPGA_FLASH_DQ3         pad K16  pin IO_L2N_T0_D03_14
# FPGA_FLASH_NCS         pad L12  pin IO_L6P_T0_FCS_B_14
# FPGA_FLASH_NRST        pad L13  pin IO_L5N_T0_D07_14
# FPGA_PUDC_B            pad L15  pin IO_L3P_T0_DQS_PUDC_B_14
# FPGA_TCK               pad L7   pin TCK_0
# FPGA_TDI               pad N7   pin TDI_0
# FPGA_TDO               pad N8   pin TDO_0
# FPGA_TMS               pad M7   pin TMS_0

# ------------------------------------------------- unresolved ports --------
# The ports above marked UNRESOLVED have no PACKAGE_PIN. Vivado will fail at
# write_bitstream ("unconstrained I/O") unless they are removed from the top level or
# the following line is enabled (ALLOWS the tool to pick pins - NOT acceptable for a
# board build, acceptable for a resource/timing trial run only):
# set_property BITSTREAM.GENERAL.UNCONSTRAINEDPINS ALLOW [current_design]

