#!/usr/bin/env python3
"""
check_manufacturing_files.py — PCB manufacturing-package inventory for AERIS-10.

For each board, checks presence of: schematic (.sch), board (.brd), Gerber set,
NC drill, pick-and-place / mount files, BOM, assembly drawing, fabrication drawing,
netlist, DRC/ERC reports. Reports a readiness table. Never creates files.

Usage:
    python3 tools/check_manufacturing_files.py [--root PATH] [--json]
Exit codes:
    0  every board has a complete package
    1  at least one board is missing manufacturing outputs (expected today)
    2  CAD directory not found
Dependencies: Python 3.8+ standard library only.
"""
import argparse
import json
import sys
from pathlib import Path

CAD = "4_Schematics and Boards Layout"
BOARDS = {
    "Main Board": {"sch_dir": f"{CAD}/4_6_Schematics/MainBoard", "stem": "RADAR_Main_Board", "prod_dir": f"{CAD}/4_7_Production Files/Main_Board", "eng_dir": "engineering/PCB/MAIN_BOARD"},
    "Power Supply": {"sch_dir": f"{CAD}/4_6_Schematics/PowerBoard", "stem": "PowerBoard", "prod_dir": f"{CAD}/4_7_Production Files/Power_Board", "eng_dir": "engineering/PCB/POWER_SUPPLY"},
    "RF Power Amplifier": {"sch_dir": f"{CAD}/4_6_Schematics/PowerAmplifierBoard", "stem": "RF_PA", "prod_dir": f"{CAD}/4_7_Production Files/RF_PA", "eng_dir": "engineering/PCB/RF_PA"},
    "Frequency Synthesizer": {"sch_dir": f"{CAD}/4_6_Schematics/FrequencySynthesizerBoard", "stem": "Clocks_Freq_Synth_board", "prod_dir": f"{CAD}/4_7_Production Files/Frequency_Synthesizer", "eng_dir": "engineering/PCB/FREQUENCY_SYNTHESIZER"},
}
# "prod_dir" = designer-released production files (the authoritative package);
# "eng_dir"  = package generated by tools/kicad_pcb_pipeline.sh (KiCad conversion), scanned with --include-generated.
GERBER_EXT = {".gbr", ".gtl", ".gbl", ".gts", ".gbs", ".gto", ".gbo", ".gtp", ".gbp", ".gko", ".gml", ".g1", ".g2", ".g3", ".g4", ".gm1", ".gpi", ".ger", ".pho", ".art"}
DRILL_EXT = {".drl", ".xln", ".drd", ".txt", ".exc", ".ncd", ".tap"}
PNP_EXT = {".mnt", ".mnb", ".pos", ".xy", ".cpl"}
BOM_EXT = {".xlsx", ".csv", ".xls", ".txt"}


def scan(root: Path, b: dict, include_generated: bool = False):
    sch_dir, prod_dir = root / b["sch_dir"], root / b["prod_dir"]
    files = []
    dirs = [sch_dir, prod_dir] + ([root / b["eng_dir"]] if include_generated else [])
    for d in dirs:
        if d.exists():
            files += [p for p in d.rglob("*") if p.is_file()]
    exts = lambda s: [p for p in files if p.suffix.lower() in s]  # noqa: E731
    names = lambda key: [p for p in files if key in p.name.lower()]  # noqa: E731
    gerbers = exts(GERBER_EXT)
    drills = [p for p in exts(DRILL_EXT) if p.suffix.lower() != ".txt" or "drill" in p.name.lower()]
    return {
        "schematic": (sch_dir / f"{b['stem']}.sch").exists(),
        "board": (sch_dir / f"{b['stem']}.brd").exists(),
        "production_dir": prod_dir.exists(),
        "gerbers": [p.name for p in gerbers],
        "drill": [p.name for p in drills],
        "pick_and_place": [p.name for p in exts(PNP_EXT) + [p for p in exts({".csv"}) if any(k in p.name.lower() for k in ("mnt", "pick_and_place", "pick-and-place", "-pos", "_pos", "cpl"))]],
        "bom": [p.name for p in exts(BOM_EXT) if "bom" in p.name.lower() or p.name.lower() in ("smd_.xlsx", "th_.xlsx")],
        "assembly_drawing": [p.name for p in names("assembly") + names("asm")],
        "fab_drawing": [p.name for p in names("fab") + names("fabrication")],
        "netlist": [p.name for p in exts({".net", ".xml", ".d356"}) if "net" in p.name.lower()],
        "drc_erc_report": [p.name for p in names("drc") + names("erc")],
        "impedance_note": [p.name for p in names("impedance")],
        "all_files": [p.relative_to(root).as_posix() for p in files],
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=Path(__file__).resolve().parent.parent)
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--include-generated", action="store_true",
                    help="also count the KiCad-generated package under engineering/PCB/<BOARD>/ (not designer-released)")
    args = ap.parse_args()
    root = Path(args.root).resolve()
    if not (root / CAD).is_dir():
        print(f"ERROR: CAD directory not found: {root / CAD}", file=sys.stderr)
        return 2
    report = {name: scan(root, b, args.include_generated) for name, b in BOARDS.items()}
    if args.include_generated and not args.json:
        print("NOTE: --include-generated counts engineering/PCB/* (KiCad conversion of the EAGLE boards, generated, not designer-released).")
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        cols = ["schematic", "board", "gerbers", "drill", "pick_and_place", "bom", "assembly_drawing", "fab_drawing", "netlist", "drc_erc_report"]
        print("| Board | " + " | ".join(cols) + " |")
        print("|---|" + "---|" * len(cols))
        for name, r in report.items():
            cells = []
            for c in cols:
                v = r[c]
                cells.append(("YES" if v else "NO") if isinstance(v, bool) else (f"YES ({len(v)})" if v else "NO"))
            print(f"| {name} | " + " | ".join(cells) + " |")
    complete = all(r["schematic"] and r["board"] and r["gerbers"] and r["drill"] and r["pick_and_place"] and r["bom"] for r in report.values())
    return 0 if complete else 1


if __name__ == "__main__":
    sys.exit(main())
