#!/usr/bin/env python3
"""
check_missing_files.py — Expected-artifact manifest checker for AERIS-10.

Checks a manifest of files/directories that a reproducible build or release
package needs (documentation tree, FPGA project files, STM32 project files,
GUI packaging files, PCB production outputs, mechanical sources).  Each entry
has an ID that matches docs/03_MISSING_COMPONENTS.md.  Never creates files.

Usage:
    python3 tools/check_missing_files.py [--root PATH] [--json] [--only-missing]
Exit codes:
    0  all P0 entries present
    1  at least one P0 entry missing
    2  root not found
Dependencies: Python 3.8+ standard library only.
"""
import argparse
import glob
import json
import sys
from pathlib import Path

CAD = "4_Schematics and Boards Layout"
# (ID, priority, description, glob pattern relative to root)
MANIFEST = [
    # --- documentation package (generated by this project) ---
    ("DOC-01", "P2", "Repository inventory", "docs/01_REPOSITORY_INVENTORY.md"),
    ("DOC-02", "P2", "Dependency map", "docs/02_DEPENDENCY_MAP.md"),
    ("DOC-03", "P2", "Missing components register", "docs/03_MISSING_COMPONENTS.md"),
    ("DOC-04", "P2", "Recovery tasks", "docs/04_RECOVERY_TASKS.md"),
    ("DOC-05", "P2", "Traceability matrix", "docs/05_TRACEABILITY_MATRIX.md"),
    ("DOC-06", "P2", "Master build manual", "docs/AERIS10_ENGINEERING_BUILD_MANUAL.md"),
    # --- FPGA ---
    ("FPGA-01", "P0", "Pin-complete XDC (no [PIN_NUMBER] placeholders)", "9_Firmware/9_2_FPGA/cntrt.xdc"),
    ("FPGA-02", "P0", "Vivado project or Tcl build script", "9_Firmware/9_2_FPGA/*.xpr"),
    ("FPGA-02b", "P0", "Vivado Tcl build script (alternative)", "9_Firmware/9_2_FPGA/build/*.tcl"),
    ("FPGA-03", "P1", "Xilinx IP (.xci) or IP catalog export", "9_Firmware/9_2_FPGA/**/*.xci"),
    ("FPGA-04", "P1", "Bitstream", "9_Firmware/9_2_FPGA/**/*.bit"),
    # --- STM32 ---
    ("STM-01", "P0", "STM32CubeMX project (.ioc)", "9_Firmware/9_1_Microcontroller/**/*.ioc"),
    ("STM-02", "P0", "Linker script", "9_Firmware/9_1_Microcontroller/**/*.ld"),
    ("STM-03", "P0", "Startup assembly", "9_Firmware/9_1_Microcontroller/**/startup_stm32*.s"),
    ("STM-04", "P0", "STM32CubeIDE project / Makefile / CMakeLists", "9_Firmware/9_1_Microcontroller/**/.cproject"),
    ("STM-04b", "P0", "Makefile (alternative)", "9_Firmware/9_1_Microcontroller/**/Makefile"),
    ("STM-04c", "P0", "CMakeLists (alternative)", "9_Firmware/9_1_Microcontroller/**/CMakeLists.txt"),
    ("STM-05", "P0", "USB Device app: usb_device.c", "9_Firmware/9_1_Microcontroller/**/usb_device.c"),
    ("STM-06", "P0", "USB Device app: usbd_cdc_if.c", "9_Firmware/9_1_Microcontroller/**/usbd_cdc_if.c"),
    ("STM-07", "P0", "USB Device app: usbd_conf.c", "9_Firmware/9_1_Microcontroller/**/usbd_conf.c"),
    ("STM-08", "P0", "USB Device app: usbd_desc.c", "9_Firmware/9_1_Microcontroller/**/usbd_desc.c"),
    ("STM-09", "P0", "STM32CubeF7 HAL driver sources", "9_Firmware/9_1_Microcontroller/**/stm32f7xx_hal.c"),
    ("STM-10", "P0", "CMSIS device header stm32f7xx.h", "9_Firmware/9_1_Microcontroller/**/stm32f7xx.h"),
    # --- GUI ---
    ("GUI-01", "P1", "requirements.txt", "9_Firmware/9_3_GUI/requirements.txt"),
    ("GUI-02", "P2", "pyproject.toml", "9_Firmware/9_3_GUI/pyproject.toml"),
    # --- PCB production ---
    ("PCB-MB-01", "P0", "Main Board Gerbers", f"{CAD}/4_7_Production Files/Main_Board/**/*.g*"),
    ("PCB-MB-02", "P0", "Main Board drill", f"{CAD}/4_7_Production Files/Main_Board/**/*.drl"),
    ("PCB-MB-03", "P0", "Main Board BOM", f"{CAD}/4_7_Production Files/Main_Board/**/*BOM*"),
    ("PCB-MB-04", "P1", "Main Board pick-and-place", f"{CAD}/4_7_Production Files/Main_Board/**/*.mnt"),
    ("PCB-PS-01", "P0", "Power Board Gerbers", f"{CAD}/4_7_Production Files/Power_Board/**/*.g*"),
    ("PCB-PS-02", "P0", "Power Board drill", f"{CAD}/4_7_Production Files/Power_Board/**/*.drl"),
    ("PCB-PS-03", "P0", "Power Board BOM", f"{CAD}/4_7_Production Files/Power_Board/**/*BOM*"),
    ("PCB-PA-01", "P0", "RF PA Gerbers", f"{CAD}/4_7_Production Files/RF_PA/**/*.g*"),
    ("PCB-PA-02", "P0", "RF PA drill", f"{CAD}/4_7_Production Files/RF_PA/**/*.drl"),
    ("PCB-PA-03", "P0", "RF PA BOM", f"{CAD}/4_7_Production Files/RF_PA/**/*BOM*"),
    ("PCB-FS-01", "P0", "Freq Synth Gerbers", f"{CAD}/4_7_Production Files/Frequency_Synthesizer/**/*.g*"),
    ("PCB-FS-02", "P0", "Freq Synth drill", f"{CAD}/4_7_Production Files/Frequency_Synthesizer/**/*.drl"),
    ("PCB-FS-03", "P0", "Freq Synth BOM", f"{CAD}/4_7_Production Files/Frequency_Synthesizer/*BOM*"),
    ("PCB-FS-04", "P1", "Freq Synth pick-and-place", f"{CAD}/4_7_Production Files/Frequency_Synthesizer/*.mnt"),
    # --- Mechanical ---
    ("MECH-01", "P1", "Assembly guide referenced by README", "10_docs/assembly_guide.md"),
    ("MECH-02", "P1", "Enclosure 3D files referenced by README", "10_docs/Hardware/Enclosure"),
    ("MECH-03", "P1", "Any STEP/STL enclosure model", "**/*.st[lp]"),
    ("MECH-04", "P2", "Antenna mechanical drawing (DXF/DWG outside simulations)", "10_docs/**/*.dxf"),
    # --- engineering drawings package (generated 2026-10-09; claude.md addendum §16-26) ---
    ("ENG-01", "P1", "Drawing register", "engineering/DRAWING_REGISTER.md"),
    ("ENG-02", "P1", "Missing-drawings recovery plan", "engineering/MISSING_DRAWINGS_RECOVERY_PLAN.md"),
    ("ENG-03", "P1", "Schematic PDF sets (4 boards)", "engineering/ELECTRICAL/schematics/*/*_schematic.pdf"),
    ("ENG-04", "P1", "Netlists (4 boards)", "engineering/ELECTRICAL/netlists/*_netlist.csv"),
    ("ENG-05", "P1", "KiCad-generated Gerber job files (4 boards)", "engineering/PCB/*/gerber/*-job.gbrjob"),
    ("ENG-06", "P1", "KiCad DRC reports (4 boards)", "engineering/PCB/*/reports/DRC_report.json"),
    ("ENG-07", "P1", "Board STEP bodies", "engineering/MECHANICAL/STEP/*.step"),
    ("ENG-08", "P1", "System block diagram (DOT)", "engineering/SYSTEM/block_diagrams/system_block_diagram.dot"),
    ("ENG-09", "P1", "Interconnection table", "engineering/SYSTEM/interfaces/interconnection_table.md"),
    ("ENG-10", "P1", "Power rail register", "engineering/ELECTRICAL/power_distribution/power_rails.md"),
    ("ENG-11", "P1", "FPGA module hierarchy (DOT)", "engineering/SOFTWARE_DIAGRAMS/FPGA/fpga_module_hierarchy.dot"),
    ("ENG-12", "P1", "Exploded view (CONCEPTUAL)", "engineering/ASSEMBLY/EXPLODED_VIEWS/aeris10_exploded_conceptual.svg"),
    ("ENG-13", "P1", "Parts list + assembly sequence", "engineering/ASSEMBLY/PARTS_LIST.md"),
    ("ENG-14", "P1", "Enclosure / antenna / pedestal CAD (designer input)", "engineering/MECHANICAL/STEP/enclosure*.step"),
    # --- repo hygiene ---
    ("REPO-01", "P2", "LICENSE file (README claims MIT)", "LICENSE*"),
    ("REPO-02", "P2", ".gitignore", ".gitignore"),
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=Path(__file__).resolve().parent.parent)
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--only-missing", action="store_true")
    args = ap.parse_args()
    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"ERROR: root not found: {root}", file=sys.stderr)
        return 2
    rows, p0_missing = [], 0
    for mid, prio, desc, pattern in MANIFEST:
        hits = [h for h in glob.glob(str(root / pattern), recursive=True) if ".git" not in h]
        if mid == "FPGA-01" and hits:  # content check: placeholders mean "present but unusable"
            txt = Path(hits[0]).read_text(errors="ignore")
            if "[PIN_NUMBER" in txt:
                hits = []
                desc += " — file exists but contains placeholders"
        present = bool(hits)
        if prio == "P0" and not present:
            p0_missing += 1
        rows.append({"id": mid, "priority": prio, "description": desc, "pattern": pattern,
                     "present": present, "hits": [str(Path(h).relative_to(root)) for h in hits[:3]]})
    if args.json:
        print(json.dumps(rows, indent=2))
    else:
        print("| ID | Prio | Component | Present | Evidence |\n|---|---|---|---|---|")
        for r in rows:
            if args.only_missing and r["present"]:
                continue
            ev = ", ".join(r["hits"]) if r["hits"] else f"no match for `{r['pattern']}`"
            print(f"| {r['id']} | {r['priority']} | {r['description']} | {'YES' if r['present'] else 'NO'} | {ev} |")
        print(f"\nP0 missing: {p0_missing}; total missing: {sum(not r['present'] for r in rows)} / {len(rows)}")
    return 1 if p0_missing else 0


if __name__ == "__main__":
    sys.exit(main())
