#!/usr/bin/env python3
"""PROPOSED DESIGN — enclosure detail drawings (no CAD needed): sheet-metal flat patterns with bend lines
(DSN-MECH-06), assembly section with fastener balloons (DSN-MECH-07) and the mechanical parts list
(MECHANICAL_PARTS_LIST.md) from the FreeCAD detail model's parts_list.json.
Bend allowance: 90°, inside radius R = t, K = 0.4 → BA = π/2·(R + K·t). Usage: python3 tools/design_enclosure_drawings.py
"""
from __future__ import annotations
import datetime as _dt, json, math, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import design_layout as L
from eagle_svg_common import SvgCanvas, Style

ROOT = L.ROOT
OUT = os.path.join(ROOT, "engineering", "DESIGN", "MECHANICAL", "drawings")
DET = os.path.join(ROOT, "engineering", "DESIGN", "MECHANICAL", "CAD", "detail")
DATE = _dt.date.today().isoformat()
W, H, D, T = L.W_IN, L.H_IN, L.D_IN, L.WALL
FL, K = 15.0, 0.4
BA = math.pi / 2 * (T + K * T)          # bend allowance per 90° bend
BLACK, BLUE, RED, GREY, GREEN = "#000", "#1f5f8b", "#b00000", "#777", "#2e7d32"
SUB = ["Units mm · scale 1:1 on the stated page · Status: PROPOSED DESIGN (D-08: Al 5754 2.5 mm, inside bend radius 2.5 mm, K-factor 0.4) · generated by tools/design_enclosure_drawings.py",
       "Flat patterns are analytical (bend allowance added at every bend, no bend reliefs drawn) — to be checked in the fabricator's CAM before cutting"]


def rect(cv, g, x, y, w, h, st, width=0.3):
    cv.polygon(g, [(x, y), (x + w, y), (x + w, y + h), (x, y + h)], width, st)


def bend(cv, g, x1, y1, x2, y2, lbl=""):
    cv.line(g, x1, y1, x2, y2, 0.25, Style(stroke=RED, dash="6,2,1,2"))
    if lbl:
        cv.text(g, (x1 + x2) / 2, (y1 + y2) / 2 + 1, lbl, 2.2, 0 if y1 == y2 else 90, "bottom-center", RED, mono=False)


def dim_h(cv, g, x1, x2, y, label):
    cv.line(g, x1, y, x2, y, 0.2, Style(stroke=BLACK)); cv.line(g, x1, y - 1.5, x1, y + 1.5, 0.2, Style(stroke=BLACK)); cv.line(g, x2, y - 1.5, x2, y + 1.5, 0.2, Style(stroke=BLACK))
    cv.text(g, (x1 + x2) / 2, y + 1.2, label, 2.6, 0, "bottom-center", BLACK, mono=False)


def dim_v(cv, g, x, y1, y2, label):
    cv.line(g, x, y1, x, y2, 0.2, Style(stroke=BLACK)); cv.line(g, x - 1.5, y1, x + 1.5, y1, 0.2, Style(stroke=BLACK)); cv.line(g, x - 1.5, y2, x + 1.5, y2, 0.2, Style(stroke=BLACK))
    cv.text(g, x + 1.2, (y1 + y2) / 2, label, 2.6, 90, "bottom-center", BLACK, mono=False)


def hole(cv, g, x, y, d):
    cv.circle(g, x, y, d / 2, 0.2, Style(stroke=BLUE, fill="none"))


sheet = Style(stroke=BLACK, fill="#f3f3f3")
# ====================== DSN-MECH-06 flat patterns ======================
cv = SvgCanvas(); g = "d"; cv.group(g)
# --- tray: base in the centre; sides unfold left/right (bend about Y edges); rear unfolds +Y; flanges beyond ---
bw, bd = W + 2 * T, D + 2 * T          # base outer size
sh = H + T                             # side height (outer)
x0, y0 = 0.0, 0.0
# base
rect(cv, g, x0, y0, bw, bd, sheet)
# left side: attached at x0, width = BA + sh + BA(flange) + FL
lx = x0 - BA - sh
rect(cv, g, lx, y0, sh, bd, sheet); bend(cv, g, x0, y0, x0, y0 + bd, "bend 90° up")
cv.polygon(g, [(x0 - BA, y0), (x0, y0), (x0, y0 + bd), (x0 - BA, y0 + bd)], 0.1, Style(stroke=RED, fill="#ffe5e5", dash="1,1"))
lfx = lx - BA - FL
rect(cv, g, lfx, y0 + T, FL, D, sheet); bend(cv, g, lx, y0, lx, y0 + bd, "bend 90° in (top flange)")
# right side
rx = x0 + bw + BA
rect(cv, g, rx, y0, sh, bd, sheet); bend(cv, g, x0 + bw, y0, x0 + bw, y0 + bd, "bend 90° up")
rect(cv, g, rx + sh + BA, y0 + T, FL, D, sheet); bend(cv, g, rx + sh, y0, rx + sh, y0 + bd, "bend 90° in (top flange)")
# rear wall unfolds in +Y, top flange beyond
ry = y0 + bd + BA
rect(cv, g, x0, ry, bw, sh, sheet); bend(cv, g, x0, y0 + bd, x0 + bw, y0 + bd, "bend 90° up")
rect(cv, g, x0 + T, ry + sh + BA, W, FL, sheet); bend(cv, g, x0, ry + sh, x0 + bw, ry + sh, "bend 90° in (rear top flange)")
# front flanges of the sides (fold toward +X/−X at the side's front edge = y0 edge of the side panels)
rect(cv, g, lx, y0 - BA - FL, sh, FL, sheet); bend(cv, g, lx, y0, lx + sh, y0, "bend 90° in (front flange)")
rect(cv, g, rx, y0 - BA - FL, sh, FL, sheet); bend(cv, g, rx, y0, rx + sh, y0, "bend 90° in (front flange)")
# holes: Ø70 cable entry in base; intake slots; lid holes in top flanges (M4 → Ø4.3 for PEM S-M4 → Ø5.4 PEM hole); front flange holes
hole(cv, g, x0 + T + W / 2, y0 + T + L.Y_POWER - 20, 70)
sw = L.FIN["strip_w"]
for sx in (L.PLATE_POS["x"], L.PLATE_POS["x"] + L.PLATE["w"] - sw):
    for k in range(6):
        rect(cv, g, x0 + T + sx + 5 + k * 8, y0 + T + L.Y_PLATE_REAR, 4, L.FIN["h"] + 2, Style(stroke=BLUE), 0.2)
for yv in range(30, int(D) - 20, 60):
    hole(cv, g, lfx + FL / 2, y0 + T + yv, 5.4); hole(cv, g, rx + sh + BA + FL / 2, y0 + T + yv, 5.4)
for xv in range(40, int(W) - 30, 60):
    hole(cv, g, x0 + T + xv, ry + sh + BA + FL / 2, 5.4)
for zv in range(30, int(H) - 20, 60):
    hole(cv, g, lx + (sh - T - zv), y0 - BA - FL / 2, 5.4); hole(cv, g, rx + T + zv, y0 - BA - FL / 2, 5.4)
# exhaust louvres in the sides near the top
for k in range(6):
    rect(cv, g, lx + 60 - k * 8 - 4, y0 + T + L.Y_PLATE_REAR + 2, 4, L.FIN["h"] - 4, Style(stroke=BLUE), 0.2)
    rect(cv, g, rx + sh - 60 + k * 8, y0 + T + L.Y_PLATE_REAR + 2, 4, L.FIN["h"] - 4, Style(stroke=BLUE), 0.2)
dim_h(cv, g, lfx, rx + sh + BA + FL, y0 - BA - FL - 10, f"{(rx + sh + BA + FL) - lfx:.1f} flat width")
dim_v(cv, g, rx + sh + BA + FL + 10, y0 - BA - FL, ry + sh + BA + FL, f"{(ry + sh + BA + FL) - (y0 - BA - FL):.1f} flat height")
cv.text(g, x0, ry + sh + BA + FL + 8, f"PART 1 — TRAY, flat pattern. Al 5754-H22 t = {T} mm; 7 bends 90°, R_in {T} mm, BA = {BA:.2f} mm each (K = {K}); PEM S-M4-1 ×{2*len(range(30,int(D)-20,60))+len(range(40,int(W)-30,60))+2*len(range(30,int(H)-20,60))} in Ø5.4 holes; corner reliefs 2×t to be added in CAM", 3.0, 0, None, BLACK, mono=False, weight="bold")
# --- front plate (flat) and lid (flat) side by side below ---
fy = y0 - BA - FL - 60 - (H + T)
rect(cv, g, x0, fy, bw, H + T, sheet)
aw, ah = L.ANT["w"] + 10, L.ANT["h"] + 10
rect(cv, g, x0 + T + L.ANT_POS["x"] - 5, fy + T + L.ANT_POS["z"] - 5, aw, ah, Style(stroke=BLUE))
for sx in (L.PLATE_POS["x"], L.PLATE_POS["x"] + L.PLATE["w"] - sw):
    for k in range(5):
        rect(cv, g, x0 + T + sx + 6, fy + T + 12 + k * 8, sw - 12, 4, Style(stroke=BLUE), 0.2)
for zv in range(30, int(H) - 20, 60):
    hole(cv, g, x0 + T + FL / 2, fy + T + zv, 4.5); hole(cv, g, x0 + T + W - FL / 2, fy + T + zv, 4.5)
ax, az = L.ANT_POS["x"] - 5, L.ANT_POS["z"] - 5
for zv in range(int(az) - 6, int(az + ah) + 7, 50):
    hole(cv, g, x0 + T + ax - 6, fy + T + zv, 3.4); hole(cv, g, x0 + T + ax + aw + 6, fy + T + zv, 3.4)
for xv in range(int(ax) + 44, int(ax + aw) - 40, 50):
    hole(cv, g, x0 + T + xv, fy + T + az - 6, 3.4); hole(cv, g, x0 + T + xv, fy + T + az + ah + 6, 3.4)
dim_h(cv, g, x0, x0 + bw, fy - 8, f"{bw:.0f}"); dim_v(cv, g, x0 + bw + 8, fy, fy + H + T, f"{H + T:.1f}")
cv.text(g, x0, fy - 14, f"PART 2 — FRONT PLATE, flat (no bends), t = {T} mm: window {aw:.0f}×{ah:.0f}, M3 clamp holes Ø3.4, M4 holes Ø4.5 to the tray front flanges, intake louvres 2 × 5", 3.0, 0, None, BLACK, mono=False, weight="bold")
ly = fy
lxx = x0 + bw + 60
rect(cv, g, lxx, ly, bw, bd, sheet)
for yv in range(30, int(D) - 20, 60):
    hole(cv, g, lxx + FL / 2, ly + T + yv, 4.5); hole(cv, g, lxx + bw - FL / 2, ly + T + yv, 4.5)
for xv in range(40, int(W) - 30, 60):
    hole(cv, g, lxx + T + xv, ly + bd - FL / 2, 4.5)
for sx in (L.PLATE_POS["x"], L.PLATE_POS["x"] + L.PLATE["w"] - sw):
    for k in range(6):
        rect(cv, g, lxx + T + sx + 5 + k * 8, ly + T + L.Y_PLATE_REAR, 4, L.FIN["h"] + 2, Style(stroke=BLUE), 0.2)
dim_h(cv, g, lxx, lxx + bw, ly - 8, f"{bw:.0f}"); dim_v(cv, g, lxx + bw + 8, ly, ly + bd, f"{bd:.1f}")
cv.text(g, lxx, ly - 14, f"PART 3 — LID, flat, t = {T} mm: M4 holes Ø4.5 on the flange pattern, exhaust slots 2 × 6; EPDM gasket 15 × 3 mm under the lid on the flanges", 3.0, 0, None, BLACK, mono=False, weight="bold")
os.makedirs(OUT, exist_ok=True)
cv.write(os.path.join(OUT, "DSN-MECH-06_sheet_metal_flat_patterns.svg"), "AERIS-10 — Radar head sheet-metal parts: flat patterns with bend lines — DSN-MECH-06 Rev A", [f"Date {DATE} · " + SUB[0], SUB[1]], margin=25)

# ====================== DSN-MECH-07 assembly section with fasteners ======================
pl = json.load(open(os.path.join(DET, "parts_list.json")))
cv = SvgCanvas(); g = "d"; cv.group(g)
wall = Style(stroke=BLACK, fill="#dddddd"); al = Style(stroke=BLACK, fill="#e8e8e8"); pcb = Style(stroke=GREEN, fill="#cfe8cf"); gask = Style(stroke="#444", fill="#333")
# side section Y (horizontal, front at left) – Z (vertical)
rect(cv, g, -T, -T, D + 2 * T, T, wall)                                   # base
rect(cv, g, D, -T, T, H + T, wall)                                          # rear wall
rect(cv, g, D - FL, H - T, FL, T, wall)                                     # rear top flange
rect(cv, g, -T, -T, T, H + T, wall)                                         # front plate
rect(cv, g, -T, H, D + 2 * T, T, wall)                                      # lid
rect(cv, g, D - FL, H - T, FL, 3, gask)                                     # lid gasket (compressed)
rect(cv, g, -T - 2.0, L.ANT_POS["z"] - 12, 2.0, L.ANT["h"] + 24, Style(stroke=BLUE, fill="#e6f0ff"))     # PTFE window
rect(cv, g, -T - 3.5, L.ANT_POS["z"] - 12, 1.5, 10, gask); rect(cv, g, -T - 3.5, L.ANT_POS["z"] + L.ANT["h"] + 2, 1.5, 10, gask)
rect(cv, g, -T - 5.5, L.ANT_POS["z"] - 14, 2.0, L.ANT["h"] + 28, al)      # clamp frame
rect(cv, g, L.Y_ANT, L.ANT_POS["z"], L.ANT["t"], L.ANT["h"], pcb)
rect(cv, g, L.Y_PLATE, L.PLATE_POS["z"], L.PLATE["t"], L.PLATE["h"], al)
rect(cv, g, L.Y_PLATE_REAR, L.PLATE_POS["z"] + 10, L.FIN["h"], L.FIN["len"], Style(stroke=GREY, dash="1,1"))
for zz in (20, H - 45):
    rect(cv, g, L.Y_PLATE - 25, zz, 25 + L.PLATE["t"], 3, al); rect(cv, g, L.Y_PLATE - 25, zz, 3, 25, al)
pa = L.pa_positions()[0]
rect(cv, g, L.Y_PA, pa[1], 1.6, L.B["RF_PA"]["h"], pcb)
sp = L.synth_pos()
for (name, y, pos, bname) in [("Main", L.Y_MAIN, L.MAIN_POS, "MAIN_BOARD"), ("Synth", L.Y_SYNTH, sp, "FREQUENCY_SYNTHESIZER"), ("Power", L.Y_POWER, L.POWER_POS, "POWER_SUPPLY")]:
    bh = L.B[bname]["h"]
    rect(cv, g, y, pos["z"], 1.6, bh, pcb)
    for zz in (pos["z"] - 10, pos["z"] + bh - 5):
        rect(cv, g, y - 12, zz, 12, 15, Style(stroke=BLACK, fill="#ccc"))
    rect(cv, g, y - 10, pos["z"] + 5, 10, 6, Style(stroke=BLACK, fill="#999")); rect(cv, g, y - 10, pos["z"] + bh - 11, 10, 6, Style(stroke=BLACK, fill="#999"))
rect(cv, g, L.Y_POWER - 70, -T - 2, 100, 2, al)
# pedestal
P = L.PEDESTAL; cy = L.Y_POWER - 20; zt = -T - P["turntable_t"]; zb = zt - P["bearing_t"]
rect(cv, g, cy - P["turntable_d"] / 2, zt, P["turntable_d"], P["turntable_t"], al)
rect(cv, g, cy - P["bearing_od"] / 2, zb, 45, P["bearing_t"], Style(stroke=BLACK, fill="#bbb")); rect(cv, g, cy + P["bearing_id"] / 2, zb, 45, P["bearing_t"], Style(stroke=BLACK, fill="#bbb"))
rect(cv, g, cy - P["base_d"] / 2, zb - 5, P["base_d"], 5, al)
rect(cv, g, cy - P["base_d"] / 2, zb - 5 - P["base_h"], P["base_d"], P["base_h"], Style(stroke=BLACK, fill="none"))
rect(cv, g, cy - P["slip_ring_od"] / 2, zb - 35, P["slip_ring_od"], P["slip_ring_len"], Style(stroke=RED, fill="#fde2e2"))
rect(cv, g, cy - 70, zb - 50, 140, 3, al)
rect(cv, g, cy - 75, zb - 5 - P["base_h"] - 10, 150, 10, Style(stroke=BLACK, fill="#bbb"))
# balloons
def balloon(n, x, y, tx, ty):
    cv.line(g, x, y, tx, ty, 0.25, Style(stroke=BLACK)); cv.circle(g, tx, ty, 4, 0.3, Style(stroke=BLACK, fill="#fff")); cv.text(g, tx, ty, str(n), 3.0, 0, "center", BLACK, mono=False, weight="bold")
items = [(1, "Tray 2.5 mm Al, 7 bends", D / 2, -T), (2, "Front plate 2.5 mm Al", -T, H / 2), (3, "Lid 2.5 mm Al", D / 2, H + T), (4, "Lid gasket EPDM 15×3", D - 7, H - T + 1.5),
         (5, "Radome window PTFE 2 mm", -T - 1, L.ANT_POS["z"] + 30), (6, "Window gasket EPDM", -T - 3, L.ANT_POS["z"] - 7), (7, "Window clamp frame 2 mm Al, M3×10 ×18", -T - 4.5, L.ANT_POS["z"] + L.ANT["h"] + 10),
         (8, "Antenna PCB 165×248 on 2.4 mm spacers, M3×6 ×6", L.Y_ANT, L.ANT_POS["z"] + 80), (9, "PA heat spreader 300×300×10, fins, M3 tapped", L.Y_PLATE + 5, 150), (10, "Plate brackets L25×25×3 ×4, M5", L.Y_PLATE - 20, 22),
         (11, "RF PA board ×16, M3×6 ×7 each, thermal pad", L.Y_PA + 1, pa[1] + 30), (12, "Carrier rails U15×12×1.5 ×6, M4×8", L.Y_MAIN - 6, L.MAIN_POS["z"] - 3), (13, "Standoffs M3×10 hex (22)", L.Y_MAIN - 5, L.MAIN_POS["z"] + 8),
         (14, "Main / Synth / Power boards (vertical)", L.Y_POWER + 1, 150), (15, "Cable-entry gland plate 100×100×2, M32 + M20 glands", L.Y_POWER - 20, -T - 2),
         (16, "Turntable Ø340×8, M6 ×8 to base", cy + 120, zt + 4), (17, "Slewing bearing OD190/ID100", cy - 70, zb + 10), (18, "Pedestal top plate 360×360×5", cy + 150, zb - 2),
         (19, "Pedestal housing 2.5 mm Al, 4 bends", cy + P["base_d"] / 2, zb - 60), (20, "Slip ring Ø99×60, 12 circuits", cy, zb - 20), (21, "Slip-ring stator bracket", cy - 60, zb - 48), (22, "Mast flange Ø150×10, 4×M10 PCD110", cy, zb - 5 - P["base_h"] - 5)]
for i, (n, _, x, y) in enumerate(items):
    tx = D + 45 + (0 if n <= 15 else 0); ty = H + 10 - 14 * (n - 1) if n <= 15 else -40 - 14 * (n - 16)
    balloon(n, x, y, tx, ty)
    cv.text(g, tx + 6, ty, items[i][1], 2.4, 0, "center-left", BLACK, mono=False)
dim_h(cv, g, -T, D + T, H + T + 12, f"{D + 2*T:.1f}"); dim_v(cv, g, D + T + 170, -T, H + T, f"{H + 2*T:.0f}")
cv.write(os.path.join(OUT, "DSN-MECH-07_assembly_section_fasteners.svg"), "AERIS-10 — Radar head and pedestal, assembly section with fasteners (front at left) — DSN-MECH-07 Rev A", [f"Date {DATE} · " + SUB[0], "Balloons → MECHANICAL_PARTS_LIST.md; sealing: lid gasket on the flanges, window gasket under the PTFE, glands at the base — IP54 target, untested"], margin=25)

# ====================== parts list ======================
fast = {}
import re as _re
for p in pl["parts"]:
    for m in _re.finditer(r"([A-Za-z][A-Za-z0-9\-]*(?:×\d+)?(?: [a-z]+)?)\s*×(\d+)", p["fasteners"]):
        fast[m.group(1).strip()] = fast.get(m.group(1).strip(), 0) + int(m.group(2))
md = [f"# AERIS-10 — Mechanical parts list (radar head + pedestal) — DSN-MECH-PL Rev A", f"\nDate {DATE} · from `CAD/detail/parts_list.json` (FreeCAD model `tools/design_enclosure_detail_freecad.py`) · Status: PROPOSED DESIGN · masses are volume × density estimates.\n",
      f"Head ≈ {pl['mass_head_g']/1000:.1f} kg (structure only, PCBs/antenna not included except as noted), pedestal ≈ {pl['mass_pedestal_g']/1000:.1f} kg (incl. stepper 1.1 kg, bearing/slip ring as modelled).\n",
      "| # | Group | Part | Material | Mass (g) | Fasteners | Note |", "|---|---|---|---|---|---|---|"]
for i, p in enumerate(pl["parts"], 1):
    md.append(f"| {i} | {p['group']} | {p['part']} | {p['material']} | {p['mass_g_estimate']:.0f} | {p['fasteners']} | {p['note']} |")
md += ["\n## Fastener totals (from the per-part lists)\n", "| Fastener | Qty |", "|---|---|"] + [f"| {k} | {v} |" for k, v in sorted(fast.items())]
md += ["\n## Sealing and finish\n", "- Lid: EPDM 15 × 3 mm self-adhesive gasket on the three top flanges, compressed to 2 mm by the M4 screws (pitch 60 mm). Front plate: 1.5 mm EPDM strip on the two front flanges (same pattern).",
       "- Radome window: PTFE 2 mm clamped by the 2 mm Al frame with EPDM 1.5 mm gasket, M3 × 18. Alternative: 2 mm Rogers/ABS radome if PTFE loss is acceptable but cost is not.",
       "- Cable entry: 100 × 100 gland plate under the base with M32 (power) and M20 (USB) IP68 glands; the Ø70 base hole lets the harness reach the slip ring rotor.",
       "- Finish: chromate conversion (Alodine) + powder coat RAL 7035 outside; bare chromate inside for grounding at the flanges; PA plate bare 6061 with thermal pads.",
       "- Open: bend reliefs and corner welds of the tray, stiffeners of the 315 mm lid (2.5 mm may need a 20 mm hem), fan mounting brackets, antenna spacer material, earthing stud, lifting points, mast interface."]
open(os.path.join(ROOT, "engineering", "DESIGN", "MECHANICAL", "MECHANICAL_PARTS_LIST.md"), "w").write("\n".join(md) + "\n")
print("drawings 06/07 + parts list written;", len(pl["parts"]), "parts; fasteners", sum(fast.values()))
