#!/usr/bin/env python3
"""PROPOSED DESIGN — block-level schematic, netlist and BOM of the 22 V PA drain supply / switch module
(DSN-PSU-01, decision D-14).  Draws an editable SVG (block schematic), writes netlist CSV and BOM.
Component-level capture in KiCad is the next step (MDR-12); values come from tools/design_thermal.py.
Usage: python3 tools/design_pa_supply_schematic.py
"""
import csv
import datetime as _dt
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from eagle_svg_common import SvgCanvas, Style  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "engineering", "DESIGN", "ELECTRICAL", "PA_SUPPLY_22V")
os.makedirs(OUT, exist_ok=True)
TH = json.load(open(os.path.join(ROOT, "engineering", "DESIGN", "THERMAL", "thermal_summary.json")))
DATE = _dt.date.today().isoformat()
cv = SvgCanvas(); g = "s"; cv.group(g)
BOX = Style(stroke="#000", fill="#f7f7f7"); NET = Style(stroke="#007a3d")
def block(x, y, w, h, title, lines, ref):
    cv.polygon(g, [(x, y), (x + w, y), (x + w, y + h), (x, y + h)], 0.4, BOX)
    cv.text(g, x + 2, y + h - 4, f"{ref}  {title}", 3.0, 0, None, "#000", mono=False, weight="bold")
    for i, l in enumerate(lines):
        cv.text(g, x + 2, y + h - 9 - 4 * i, l, 2.4, 0, None, "#333", mono=False)
def wire(x1, y1, x2, y2, name, w=0.5):
    cv.line(g, x1, y1, x2, y2, w, NET); cv.text(g, (x1 + x2) / 2, max(y1, y2) + 1.2, name, 2.4, 0, "bottom-center", "#007a3d", mono=False)
# blocks
block(0, 60, 40, 24, "VIN input", ["12–17 V from slip ring", "2 × 16 AWG, fuse F1 20 A", "TVS D1 SMBJ18A"], "J1")
wire(40, 72, 55, 72, "VIN_RAW")
block(55, 60, 45, 24, "EMI filter", ["L_cm 10 µH 15 A", "C 4×4.7 µF X7R 50 V", "π-filter, Y caps to chassis"], "FL1")
wire(100, 72, 115, 72, "VIN_F")
block(115, 50, 70, 44, "2-phase sync boost 12–17 V → 22 V", ["U1,U2 LM5122 (interleaved 180°)", "Q1–Q4 CSD19532Q5B 100 V", "L1,L2 10 µH 15 A (XAL1580)", "Cout 4×100 µF/35 V polymer + 2×1000 µF", "fsw 300 kHz; Iout 8 A cont.; PGOOD"], "U1/U2")
wire(185, 72, 200, 72, "22V_BUS")
block(200, 50, 60, 44, "Hot-swap / enable switch", ["U3 LM5069-1, Q5 CSD19536KTT", "Rs 2 mΩ → I_lim 12 A avg", "dV/dt 1 ms, UVLO 20 V", "EN ← EN/DIS_RFPA_VDD (STM32)", "PGOOD/FAULT → MCU GPIO"], "U3")
wire(260, 72, 275, 72, "22V_SW")
block(275, 30, 70, 64, "Pulse gate ×16 (one per PA)", ["U4..U19 LTC7003 high-side driver (≤100 ns)", "Q6..Q21 CSD19532Q5B (N-FET, high side)", "C_loc 220 µF/35 V polymer per channel", "TX_GATE ← FPGA spare I/O (UNRESOLVED pin)", f"peak {TH['i_peak_a']:.0f} A total, {TH['duty_gate']*100:.1f} % duty", "OUT1..OUT16 → AK300/2 on each PA board"], "U4–U19")
for i in range(16):
    y = 30 + 2 + i * 3.8
    cv.line(g, 345, y, 360, y, 0.4, NET)
cv.text(g, 362, 60, "OUT1..OUT16 → PA1..PA16 `22V` (CBL-xxx, 18 AWG twisted)", 2.4, 0, "center-left", "#007a3d", mono=False)
# control lines
cv.line(g, 230, 50, 230, 20, 0.4, Style(stroke="#1f5f8b", dash="2,1")); cv.text(g, 230, 17, "EN/DIS_RFPA_VDD (STM32, 3.3 V)", 2.4, 0, "top-center", "#1f5f8b", mono=False)
cv.line(g, 310, 30, 310, 10, 0.4, Style(stroke="#1f5f8b", dash="2,1")); cv.text(g, 310, 7, "TX_GATE (FPGA, 3.3 V LVCMOS, active during each chirp ±5 µs)", 2.4, 0, "top-center", "#1f5f8b", mono=False)
cv.line(g, 150, 50, 150, 20, 0.4, Style(stroke="#1f5f8b", dash="2,1")); cv.text(g, 150, 17, "PGOOD_22V → MCU", 2.4, 0, "top-center", "#1f5f8b", mono=False)
cv.text(g, 0, 104, "Sequencing (existing firmware + this module): VG −4 V (DAC5578) → EN/DIS_RFPA_VDD high → U3 ramps 22V_SW → TX_GATE pulses drain only during chirps. Power-down reverse. Thermal/RF reasoning: engineering/DESIGN/THERMAL/THERMAL_AND_PA_SUPPLY.md.", 2.4, 0, None, "#333", mono=False)
cv.text(g, 0, 100, "GND: single star at the module; chassis bond at FL1 Y-caps. Module footprint 120 × 80 mm, 25 mm high, mounted on the rear wall (DSN-MECH-01).", 2.4, 0, None, "#333", mono=False)
cv.write(os.path.join(OUT, "DSN-PSU-01_block_schematic.svg"), "AERIS-10 — 22 V PA drain supply, enable switch and per-PA pulse gating — DSN-PSU-01 Rev A — STATUS: PROPOSED DESIGN (block level)",
         [f"Date {DATE} · generated by tools/design_pa_supply_schematic.py · decision D-14 (00_DESIGN_BASIS.md) · sizing from tools/design_thermal.py",
          "Block-level only: component-level schematic, layout and protection detail must be captured in KiCad (MDR-12). Part numbers are proposals (availability to be verified)."], margin=10)
bom = [
    ("J1", 1, "DC input terminal 2-pole 16 A", "Phoenix 1792270 or AK300/2", "input"),
    ("F1", 1, "Fuse 20 A 32 V automotive", "Littelfuse 0297020", "input"),
    ("D1", 1, "TVS 18 V SMB", "SMBJ18A", "input"),
    ("FL1", 1, "CM choke 10 µH 15 A + 4×4.7 µF/50 V X7R", "Würth 744 823 110 / GRM32ER71H475K", "filter"),
    ("U1,U2", 2, "Sync boost controller", "TI LM5122MH", "boost"),
    ("Q1–Q4", 4, "N-MOSFET 100 V 100 A", "TI CSD19532Q5B", "boost"),
    ("L1,L2", 2, "Inductor 10 µH 15 A", "Coilcraft XAL1580-103", "boost"),
    ("C_out", 4, "Polymer 100 µF/35 V", "Panasonic 35SVPF100M", "boost"),
    ("C_bulk", 2, "Electrolytic 1000 µF/35 V low ESR", "Nichicon UHE1V102MHD", "boost/bulk"),
    ("U3", 1, "Hot-swap controller 9–80 V", "TI LM5069MM-1", "switch"),
    ("Q5", 1, "N-MOSFET 100 V 200 A D2PAK", "TI CSD19536KTT", "switch"),
    ("Rs", 1, "Sense 2 mΩ 3 W", "Bourns CSS2H-2512R-L200F", "switch"),
    ("U4–U19", 16, "High-side gate driver ≤ 100 ns", "ADI LTC7003", "gate"),
    ("Q6–Q21", 16, "N-MOSFET 100 V", "TI CSD19532Q5B", "gate"),
    ("C_loc", 16, "Polymer 220 µF/35 V", "Panasonic 35SVPF220M (or on each PA board)", "gate"),
    ("OUT1–16", 16, "Screw terminal 2-pole", "AK300/2 (matches the PA board)", "output"),
]
with open(os.path.join(OUT, "DSN-PSU-01_BOM.csv"), "w", newline="", encoding="utf-8") as fh:
    w = csv.writer(fh); w.writerow(["ref", "qty", "description", "proposed_part", "section"]); w.writerows(bom)
nets = [("VIN_RAW", "J1.1, F1.1"), ("VIN_F", "F1.2 → FL1.in; FL1.out → U1/U2 VIN, L1/L2"), ("22V_BUS", "Q2/Q4 drains, C_out, C_bulk, U3 VIN, Rs"),
        ("22V_SW", "Q5 source → U4..U19 VIN, Q6..Q21 drains"), ("OUT1..OUT16", "Q6..Q21 sources → C_loc → OUTn.1"), ("GND", "star; J1.2, FL1, U1/U2/U3 GND, OUTn.2, chassis via Y caps"),
        ("EN/DIS_RFPA_VDD", "STM32 GPIO (main.h) → U3 EN (level-shift 3.3 V → UVLO pin)"), ("TX_GATE", "FPGA spare I/O → U4..U19 IN (buffered 74LVC2G34)"), ("PGOOD_22V", "U1 PGOOD & U3 PGD (open-drain, wired-AND) → MCU GPIO (to allocate)")]
with open(os.path.join(OUT, "DSN-PSU-01_netlist.csv"), "w", newline="", encoding="utf-8") as fh:
    w = csv.writer(fh); w.writerow(["net", "connections"]); w.writerows(nets)
open(os.path.join(OUT, "README.md"), "w", encoding="utf-8").write(f"""# DSN-PSU-01 — 22 V PA drain supply, enable switch and per-PA pulse gating (PROPOSED DESIGN)

Rev A · {DATE} · closes conflict K4 (22 V PA supply not in CAD) per decision D-14. Block schematic `DSN-PSU-01_block_schematic.svg` (+ PDF/PNG), BOM `DSN-PSU-01_BOM.csv`, net summary `DSN-PSU-01_netlist.csv`.

| Requirement | Value | Source |
|---|---|---|
| Input | 12–17 V (system VIN via slip ring) | xlsx VIN |
| Output | 22 V ± 2 %, 8 A continuous, {TH['i_peak_a']:.0f} A pulsed ({TH['duty_gate']*100:.1f} % duty) | QPA2962 datasheet, timing |
| Bulk energy | ≥ {TH['c_bulk_uF']:.0f} µF total for ΔV ≤ 0.5 V per 30 µs chirp | `THERMAL_AND_PA_SUPPLY.md` §5 |
| Enable | `EN/DIS_RFPA_VDD` (existing STM32 pin) → hot-swap switch | `main.h` |
| Pulse gate | `TX_GATE` from the FPGA — **spare pin to allocate (UNRESOLVED)**; without it the system runs case A (591 W) | D-14 |
| Telemetry | PGOOD/FAULT to the MCU (pin to allocate); per-PA drain current already measured by INA241 on the Main Board | schematic |
| Mechanical | 120 × 80 × 25 mm on the head rear wall (DSN-MECH-01) | layout |

Next steps (MDR-12): KiCad component-level schematic → layout (4-layer, 2 oz) → bench test of one gate channel with a 30 µs / 45 A dummy load → EMC pre-check of the boost.
""")
print("PSU schematic written")
