#!/usr/bin/env python3
"""PROPOSED DESIGN — 2-D engineering drawings (SVG, scale 1:1) of the AERIS-10 head and pedestal
plus the harness schedule, from tools/design_layout.py (no CAD application needed).

Outputs in engineering/DESIGN/MECHANICAL/drawings/:
  DSN-MECH-01_head_plan_section.svg     plan section at mid height (X–Y)
  DSN-MECH-02_head_front_elevation.svg  front elevation (X–Z) with radome window and ducts
  DSN-MECH-03_head_side_section.svg     side section (Y–Z) incl. pedestal
  DSN-MECH-04_internal_layout_rear.svg  internal layout: every tier seen from the rear with connector positions (P&P)
  DSN-MECH-05_pedestal_plan.svg         pedestal plan (bearing, pulley, belt, stepper, slip ring)
and in engineering/DESIGN/HARNESS/: harness_schedule.csv / HARNESS_SCHEDULE.md (computed lengths).
Usage: python3 tools/design_mechanical_drawings.py
"""
from __future__ import annotations

import csv
import datetime as _dt
import math
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import design_layout as L  # noqa: E402
from eagle_svg_common import SvgCanvas, Style  # noqa: E402

ROOT = L.ROOT
OUT = os.path.join(ROOT, "engineering", "DESIGN", "MECHANICAL", "drawings")
HOUT = os.path.join(ROOT, "engineering", "DESIGN", "HARNESS")
os.makedirs(OUT, exist_ok=True)
os.makedirs(HOUT, exist_ok=True)
DATE = _dt.date.today().isoformat()
BLACK, BLUE, RED, GREY, GREEN, ORANGE = "#000", "#1f5f8b", "#b00000", "#777", "#2e7d32", "#c8781e"
SUB = ["Units mm · scale 1:1 on the stated page · Status: PROPOSED DESIGN (decisions D-07…D-13 in engineering/DESIGN/00_DESIGN_BASIS.md) · generated by tools/design_mechanical_drawings.py",
       "Board outlines and connector positions are VERIFIED (EAGLE .brd / KiCad P&P); enclosure, spacing, pedestal and fasteners are PROPOSED; component heights ASSUMED 15 mm"]


def rect(cv, g, x, y, w, h, st, width=0.3):
    cv.polygon(g, [(x, y), (x + w, y), (x + w, y + h), (x, y + h)], width, st)


def dim_h(cv, g, x1, x2, y, label, off=4):
    cv.line(g, x1, y, x2, y, 0.2, Style(stroke=BLACK))
    cv.line(g, x1, y - 1.5, x1, y + 1.5, 0.2, Style(stroke=BLACK))
    cv.line(g, x2, y - 1.5, x2, y + 1.5, 0.2, Style(stroke=BLACK))
    cv.text(g, (x1 + x2) / 2, y + 1.2, label, 2.6, 0, "bottom-center", BLACK, mono=False)


def dim_v(cv, g, x, y1, y2, label):
    cv.line(g, x, y1, x, y2, 0.2, Style(stroke=BLACK))
    cv.line(g, x - 1.5, y1, x + 1.5, y1, 0.2, Style(stroke=BLACK))
    cv.line(g, x - 1.5, y2, x + 1.5, y2, 0.2, Style(stroke=BLACK))
    cv.text(g, x + 1.2, (y1 + y2) / 2, label, 2.6, 90, "bottom-center", BLACK, mono=False)


def label(cv, g, x, y, s, size=2.6, color=BLACK, align=None, w="normal"):
    cv.text(g, x, y, s, size, 0, align, color, mono=False, weight=w)


W, H, D, T = L.W_IN, L.H_IN, L.D_IN, L.WALL
wall = Style(stroke=BLACK, fill="#dddddd")
pcb = Style(stroke=GREEN, fill="#cfe8cf")
al = Style(stroke=BLACK, fill="#e8e8e8")
dash = Style(stroke=GREY, dash="2,1.5")
sw = L.FIN["strip_w"]

# ---------------- 01 plan section ----------------
cv = SvgCanvas(); g = "d"; cv.group(g)
rect(cv, g, -T, -T, W + 2 * T, D + 2 * T, wall); rect(cv, g, 0, 0, W, D, Style(stroke=BLACK, fill="#fff"))
rect(cv, g, L.ANT_POS["x"] - 5, -T, L.ANT["w"] + 10, T, Style(stroke=BLACK, fill="#fff"))   # radome opening
rect(cv, g, L.ANT_POS["x"] - 5, -T, L.ANT["w"] + 10, 2, Style(stroke=BLUE, fill="#e6f0ff"))   # PTFE window
label(cv, g, L.ANT_POS["x"], -T - 3, "radome window PTFE 2 mm", 2.4, BLUE)
rect(cv, g, L.ANT_POS["x"], L.Y_ANT, L.ANT["w"], L.ANT["t"], pcb); label(cv, g, L.ANT_POS["x"] + L.ANT["w"] + 2, L.Y_ANT - 0.5, "antenna PCB 165×248×0.6 (DSN-ANT-01)", 2.4, GREEN)
rect(cv, g, L.PLATE_POS["x"], L.Y_PLATE, L.PLATE["w"], L.PLATE["t"], al)
nf = int(sw // L.FIN["pitch"])
for sx in (L.PLATE_POS["x"], L.PLATE_POS["x"] + L.PLATE["w"] - sw):
    for i in range(nf):
        fx = sx + i * L.FIN["pitch"] + (L.FIN["pitch"] - L.FIN["t"]) / 2
        rect(cv, g, fx, L.Y_PLATE_REAR, L.FIN["t"], L.FIN["h"], al, 0.15)
label(cv, g, L.PLATE_POS["x"] + 2, L.Y_PLATE + 3.5, f"heat spreader Al 300×300×{L.PLATE['t']:.0f}, fin fields {nf}×2 ({L.FIN['h']:.0f} mm, pitch {L.FIN['pitch']:.0f})", 2.4)
zmid = 180.0
for i, (px, pz) in enumerate(L.pa_positions(), 1):
    if pz <= zmid <= pz + L.B["RF_PA"]["h"]:
        rect(cv, g, px, L.Y_PA, L.B["RF_PA"]["w"], 1.6, pcb); rect(cv, g, px + 3, L.Y_PA + 1.6, L.B["RF_PA"]["w"] - 6, 10, dash)
        label(cv, g, px + 2, L.Y_PA + 13, f"PA{i}", 2.2, GREEN)
rect(cv, g, L.MAIN_POS["x"], L.Y_MAIN, L.B["MAIN_BOARD"]["w"], 1.6, pcb); rect(cv, g, L.MAIN_POS["x"] + 5, L.Y_MAIN + 1.6, L.B["MAIN_BOARD"]["w"] - 10, 15, dash)
label(cv, g, L.MAIN_POS["x"] + 2, L.Y_MAIN + 18.5, "Main Board 260×300 (vertical), components → rear, envelope 15 (ASSUMED)", 2.4, GREEN)
sp = L.synth_pos()
rect(cv, g, sp["x"], L.Y_SYNTH, 100, 1.6, pcb); rect(cv, g, sp["x"] + 3, L.Y_SYNTH + 1.6, 94, 12, dash)
label(cv, g, sp["x"] + 2, L.Y_SYNTH + 15.5, f"Synth 100×100 at x={sp['x']:.0f} ({sp['basis']})", 2.4, GREEN)
rect(cv, g, L.POWER_POS["x"], L.Y_POWER, 280, 1.6, pcb); rect(cv, g, L.POWER_POS["x"] + 5, L.Y_POWER + 1.6, 270, 15, dash)
label(cv, g, L.POWER_POS["x"] + 2, L.Y_POWER + 18.5, "Power Board 280×300 (vertical)", 2.4, GREEN)
rect(cv, g, W - 130, L.Y_POWER + 1.6, 120, 20, Style(stroke=ORANGE, dash="2,1")); label(cv, g, W - 128, L.Y_POWER + 23, "22 V PA supply/gate module DSN-PSU-01 (z 220..300)", 2.2, ORANGE)
cv.circle(g, W / 2, L.Y_POWER - 20, 35, 0.3, Style(stroke=RED, dash="3,2")); label(cv, g, W / 2 + 37, L.Y_POWER - 20, "Ø70 slip-ring passage in the base (rotation axis)", 2.4, RED)
dim_h(cv, g, -T, W + T, D + T + 10, f"{W + 2*T:.0f} outer width"); dim_h(cv, g, 0, W, D + T + 4, f"{W:.0f} inner")
dim_v(cv, g, W + T + 10, -T, D + T, f"{D + 2*T:.1f} outer depth")
for yv, nm in [(L.Y_ANT, "antenna"), (L.Y_PLATE, "plate"), (L.Y_PA, "PA"), (L.Y_MAIN, "Main"), (L.Y_SYNTH, "Synth"), (L.Y_POWER, "Power")]:
    cv.line(g, -T - 14, yv, -T, yv, 0.15, Style(stroke=GREY)); label(cv, g, -T - 15, yv, f"y={yv:.1f} {nm}", 2.2, GREY, "center-right")
cv.write(os.path.join(OUT, "DSN-MECH-01_head_plan_section.svg"), "AERIS-10 — Radar head, plan section at z = 180 mm (looking down) — DSN-MECH-01 Rev A", [f"Date {DATE} · " + SUB[0], SUB[1]], margin=20)

# ---------------- 02 front elevation ----------------
cv = SvgCanvas(); g = "d"; cv.group(g)
rect(cv, g, -T, -T, W + 2 * T, H + 2 * T, wall)
rect(cv, g, L.ANT_POS["x"] - 5, L.ANT_POS["z"] - 5, L.ANT["w"] + 10, L.ANT["h"] + 10, Style(stroke=BLUE, fill="#e6f0ff"))
rect(cv, g, L.ANT_POS["x"], L.ANT_POS["z"], L.ANT["w"], L.ANT["h"], Style(stroke=GREEN, fill="none", dash="2,1.5"))
pitch = L.P["rf"]["element_pitch_mm"]["value"]
for i in range(16):
    yc = L.ANT_POS["z"] + 12 + 9.35 / 2 + i * pitch
    rect(cv, g, L.ANT_POS["x"] + 36, yc - 9.35 / 2, 123, 9.35, Style(stroke=ORANGE, fill="#f7e0c3", opacity=0.8), 0.1)
label(cv, g, L.ANT_POS["x"], L.ANT_POS["z"] + L.ANT["h"] + 7, "radome window 175×258 (PTFE) over the 16×8 patch array; rows at 14.3 mm", 2.4, BLUE)
for sx in (L.PLATE_POS["x"], L.PLATE_POS["x"] + L.PLATE["w"] - sw):
    for k in range(8):
        rect(cv, g, sx + 5, H - 2 - 40 - k * 6, sw - 10, 2.5, Style(stroke=GREY, fill="#fff"), 0.15)   # exhaust louvres (top of side ducts)
        rect(cv, g, sx + 5, 10 + k * 6, sw - 10, 2.5, Style(stroke=GREY, fill="#fff"), 0.15)             # intake louvres
    label(cv, g, sx + 5, 62, "intake louvres + 60 mm fan", 2.0, GREY); label(cv, g, sx + 5, H - 44, "exhaust louvres", 2.0, GREY)
dim_h(cv, g, -T, W + T, H + T + 10, f"{W + 2*T:.0f}"); dim_v(cv, g, W + T + 10, -T, H + T, f"{H + 2*T:.0f}")
dim_h(cv, g, L.ANT_POS["x"], L.ANT_POS["x"] + L.ANT["w"], -T - 8, f"{L.ANT['w']:.0f} antenna")
dim_v(cv, g, -T - 8, L.ANT_POS["z"], L.ANT_POS["z"] + L.ANT["h"], f"{L.ANT['h']:.0f}")
cv.write(os.path.join(OUT, "DSN-MECH-02_head_front_elevation.svg"), "AERIS-10 — Radar head, front elevation (antenna side) — DSN-MECH-02 Rev A", [f"Date {DATE} · " + SUB[0], SUB[1]], margin=20)

# ---------------- 03 side section (Y–Z) incl. pedestal ----------------
cv = SvgCanvas(); g = "d"; cv.group(g)
# draw with Y horizontal (front at left), Z vertical
rect(cv, g, -T, -T, D + 2 * T, H + 2 * T, wall); rect(cv, g, 0, 0, D, H, Style(stroke=BLACK, fill="#fff"))
rect(cv, g, -T, L.ANT_POS["z"] - 5, 2, L.ANT["h"] + 10, Style(stroke=BLUE, fill="#e6f0ff"))
rect(cv, g, L.Y_ANT, L.ANT_POS["z"], L.ANT["t"], L.ANT["h"], pcb)
rect(cv, g, L.Y_PLATE, L.PLATE_POS["z"], L.PLATE["t"], L.PLATE["h"], al)
rect(cv, g, L.Y_PLATE_REAR, L.PLATE_POS["z"] + 10, L.FIN["h"], L.FIN["len"], Style(stroke=GREY, dash="1,1"))
for i, (px, pz) in enumerate(L.pa_positions(), 1):
    if i % 4 == 1:
        rect(cv, g, L.Y_PA, pz, 1.6, L.B["RF_PA"]["h"], pcb); rect(cv, g, L.Y_PA + 1.6, pz + 5, 10, L.B["RF_PA"]["h"] - 10, dash)
rect(cv, g, L.Y_MAIN, L.MAIN_POS["z"], 1.6, 300, pcb); rect(cv, g, L.Y_MAIN + 1.6, 10, 15, 290, dash)
rect(cv, g, L.Y_SYNTH, sp["z"], 1.6, 100, pcb); rect(cv, g, L.Y_SYNTH + 1.6, sp["z"] + 3, 12, 94, dash)
rect(cv, g, L.Y_POWER, 5, 1.6, 300, pcb); rect(cv, g, L.Y_POWER + 1.6, 10, 15, 290, dash)
rect(cv, g, L.Y_PLATE_REAR - 2, 0, 29, 15, Style(stroke=GREY, fill="#fff")); label(cv, g, L.Y_PLATE_REAR - 2, 17, "fan", 2.0, GREY)
# pedestal
P = L.PEDESTAL
cy = L.Y_POWER - 20
rect(cv, g, cy - P["turntable_d"] / 2, -T - P["turntable_t"], P["turntable_d"], P["turntable_t"], al)
zb = -T - P["turntable_t"] - P["bearing_t"]
rect(cv, g, cy - P["bearing_od"] / 2, zb, (P["bearing_od"] - P["bearing_id"]) / 2, P["bearing_t"], Style(stroke=BLACK, fill="#c9c9c9"))
rect(cv, g, cy + P["bearing_id"] / 2, zb, (P["bearing_od"] - P["bearing_id"]) / 2, P["bearing_t"], Style(stroke=BLACK, fill="#c9c9c9"))
rect(cv, g, cy - P["slip_ring_od"] / 2, zb - 30, P["slip_ring_od"], P["slip_ring_len"], Style(stroke=RED, fill="#fde2e2"))
rect(cv, g, cy - P["base_d"] / 2, zb - P["base_h"], P["base_d"], P["base_h"], Style(stroke=BLACK, fill="none"))
rect(cv, g, cy - P["base_d"] / 2 + T, zb - P["base_h"] + T, P["base_d"] - 2 * T, P["base_h"] - 2 * T, Style(stroke=BLACK, fill="none"))
rect(cv, g, cy - 28.2, zb - 20 - 76, 56.4, 76, Style(stroke=BLACK, fill="#bbb")); label(cv, g, cy - 28, zb - 100, "NEMA 23 (behind the section plane)", 2.0, GREY)
rect(cv, g, cy - 75, zb - P["base_h"] - 10, 150, 10, Style(stroke=BLACK, fill="#c9c9c9")); label(cv, g, cy + 78, zb - P["base_h"] - 8, "mast flange Ø150 (ASSUMPTION)", 2.2, GREY)
label(cv, g, cy + P["turntable_d"] / 2 + 3, -T - 6, "turntable Ø340×8", 2.2); label(cv, g, cy + P["bearing_od"] / 2 + 3, zb + 4, "slewing bearing OD190/ID100", 2.2); label(cv, g, cy + P["slip_ring_od"] / 2 + 3, zb - 20, "slip ring Ø99×60, 12 circuits", 2.2, RED)
dim_h(cv, g, -T, D + T, H + T + 10, f"{D + 2*T:.1f} head depth"); dim_v(cv, g, D + T + 12, -T, H + T, f"{H + 2*T:.0f}"); dim_v(cv, g, D + T + 12, zb - P["base_h"] - 10, -T, f"{T + P['turntable_t'] + P['bearing_t'] + P['base_h'] + 10:.1f} pedestal")
for yv, nm in [(L.Y_ANT, "antenna"), (L.Y_PLATE, "plate"), (L.Y_MAIN, "Main"), (L.Y_SYNTH, "Synth"), (L.Y_POWER, "Power")]:
    label(cv, g, yv, H + T + 3, nm, 2.0, GREY, "bottom-center")
cv.write(os.path.join(OUT, "DSN-MECH-03_head_side_section.svg"), "AERIS-10 — Radar head and pedestal, side section (front at left) — DSN-MECH-03 Rev A", [f"Date {DATE} · " + SUB[0], SUB[1]], margin=20)

# ---------------- 04 internal layout, rear views per tier with connectors ----------------
cv = SvgCanvas(); g = "d"; cv.group(g)
tiers = [("Tier 1 — PA heat spreader (rear face): 16 PA boards + fin fields", None), ("Tier 2 — Main Board (rear = component side)", "MAIN_BOARD"),
         ("Tier 3 — Frequency Synthesizer", "FREQUENCY_SYNTHESIZER"), ("Tier 4 — Power Board", "POWER_SUPPLY")]
xoff = 0
conn_re = re.compile(r"^(J|X|JP|SV|X_)\d*$|^X_\d+$")
for title, board in tiers:
    rect(cv, g, xoff, 0, W, H, Style(stroke=BLACK, fill="#fafafa"))
    label(cv, g, xoff, H + 4, title, 3.0, BLACK, None, "bold")
    if board is None:
        rect(cv, g, xoff + L.PLATE_POS["x"], L.PLATE_POS["z"], L.PLATE["w"], L.PLATE["h"], al)
        for sx in (L.PLATE_POS["x"], L.PLATE_POS["x"] + L.PLATE["w"] - sw):
            rect(cv, g, xoff + sx, L.PLATE_POS["z"] + 10, sw, L.FIN["len"], Style(stroke=GREY, fill="#f0f0f0", dash="1,1"))
            label(cv, g, xoff + sx + 2, L.PLATE_POS["z"] + 12, "fins", 2.0, GREY)
        for i, (px, pz) in enumerate(L.pa_positions(), 1):
            rect(cv, g, xoff + px, pz, L.B["RF_PA"]["w"], L.B["RF_PA"]["h"], pcb)
            label(cv, g, xoff + px + 2, pz + L.B["RF_PA"]["h"] - 6, f"PA{i}", 2.6, GREEN, None, "bold")
        dim_h(cv, g, xoff + L.PA_FIELD["x"], xoff + L.PA_FIELD["x"] + L.PA_GRID["pitch_x"], H - 4, f"{L.PA_GRID['pitch_x']:.0f} pitch")
        dim_v(cv, g, xoff + L.PA_FIELD["x"] - 4, L.PA_FIELD["z"], L.PA_FIELD["z"] + L.PA_GRID["pitch_z"], f"{L.PA_GRID['pitch_z']:.0f}")
    else:
        bw, bh = L.B[board]["w"], L.B[board]["h"]
        pos = {"MAIN_BOARD": L.MAIN_POS, "POWER_SUPPLY": L.POWER_POS, "FREQUENCY_SYNTHESIZER": sp}[board]
        rect(cv, g, xoff + pos["x"], pos["z"], bw, bh, pcb)
        pnp = L.load_pnp(board)
        for ref, (bx, by, side) in pnp.items():
            if conn_re.match(ref) or ref.startswith("X_") or ref in ("SV1",):
                hx, hz = xoff + pos["x"] + bx, pos["z"] + by
                cv.circle(g, hx, hz, 1.2, 0.2, Style(stroke=BLUE, fill="#fff"))
                label(cv, g, hx + 1.5, hz, ref, 1.6, BLUE)
        label(cv, g, xoff + pos["x"], pos["z"] - 4, f"origin x={pos['x']:.0f}, z={pos['z']:.0f}; connectors from KiCad P&P (seen from the rear = component side; X mirrored vs. front)", 2.0, GREY)
    xoff += W + 30
cv.write(os.path.join(OUT, "DSN-MECH-04_internal_layout_rear.svg"), "AERIS-10 — Internal layout, each tier seen from the rear, with connector positions — DSN-MECH-04 Rev A", [f"Date {DATE} · " + SUB[0], SUB[1] + " · connector refs: J/X/JP/SV from the P&P files"], margin=20)

# ---------------- 05 pedestal plan ----------------
cv = SvgCanvas(); g = "d"; cv.group(g)
cx, cy = W / 2, L.Y_POWER - 20
rect(cv, g, cx - P["base_w"] / 2, cy - P["base_d"] / 2, P["base_w"], P["base_d"], Style(stroke=BLACK, fill="none"))
cv.circle(g, cx, cy, P["turntable_d"] / 2, 0.3, Style(stroke=GREY, dash="3,2")); label(cv, g, cx + P["turntable_d"] / 2 - 60, cy + P["turntable_d"] / 2 + 3, "turntable Ø340 (above)", 2.2, GREY)
cv.circle(g, cx, cy, P["bearing_od"] / 2, 0.3, Style(stroke=BLACK)); cv.circle(g, cx, cy, P["bearing_id"] / 2, 0.3, Style(stroke=BLACK))
cv.circle(g, cx, cy, P["ring_pulley_d"] / 2, 0.3, Style(stroke=ORANGE)); cv.circle(g, cx, cy, P["slip_ring_od"] / 2, 0.3, Style(stroke=RED))
mx = cx + P["ring_pulley_d"] / 2 + P["motor_pulley_d"] / 2 + 25
rect(cv, g, mx - 28.2, cy - 28.2, 56.4, 56.4, Style(stroke=BLACK, fill="#ddd")); cv.circle(g, mx, cy, P["motor_pulley_d"] / 2, 0.3, Style(stroke=ORANGE))
# belt (two tangent lines)
r1, r2 = P["ring_pulley_d"] / 2, P["motor_pulley_d"] / 2
dcc = mx - cx; a = math.acos((r1 - r2) / dcc)
for sgn in (1, -1):
    cv.line(g, cx + r1 * math.cos(a) * 1, cy + sgn * r1 * math.sin(a), mx + r2 * math.cos(a), cy + sgn * r2 * math.sin(a), 0.6, Style(stroke=ORANGE))
label(cv, g, cx - 60, cy + r1 + 4, f"ring pulley {P['ring_teeth']}T GT3 Ø{P['ring_pulley_d']:.0f}", 2.2, ORANGE); label(cv, g, mx - 30, cy - 40, f"NEMA 23 + {P['motor_teeth']}T pulley, ratio 1:{P['ratio']}", 2.2)
label(cv, g, cx - 45, cy - r1 - 8, f"slewing bearing OD{P['bearing_od']:.0f}/ID{P['bearing_id']:.0f}", 2.2); label(cv, g, cx + 10, cy, "slip ring Ø99", 2.0, RED)
rect(cv, g, cx - 150, cy + 80, 96, 72, Style(stroke=BLACK, fill="#eee")); label(cv, g, cx - 148, cy + 155, "TB6600 driver", 2.2)
rect(cv, g, cx - 150, cy - 150, 60, 40, Style(stroke=BLACK, fill="#eee")); label(cv, g, cx - 148, cy - 107, "DC input / USB bulkhead", 2.2)
for k in range(4):
    ang = math.radians(45 + 90 * k); cv.circle(g, cx + 55 * math.cos(ang), cy + 55 * math.sin(ang), 5.5, 0.2, Style(stroke=GREY, dash="1,1"))
label(cv, g, cx + 60, cy - 70, "mast flange 4×M10 PCD110 (below, ASSUMPTION)", 2.0, GREY)
dim_h(cv, g, cx - P["base_w"] / 2, cx + P["base_w"] / 2, cy + P["base_d"] / 2 + 10, f"{P['base_w']:.0f}")
label(cv, g, cx - P["base_w"] / 2, cy - P["base_d"] / 2 - 6, f"firmware change required with ratio 1:{P['ratio']}: {P['firmware_change']}", 2.2, RED)
cv.write(os.path.join(OUT, "DSN-MECH-05_pedestal_plan.svg"), "AERIS-10 — Pedestal plan (turntable removed) — DSN-MECH-05 Rev A", [f"Date {DATE} · " + SUB[0], "Pedestal is PROPOSED (D-12, D-13); stepper/driver from firmware + xlsx; bearing, pulleys, slip ring are generic part classes to be selected"], margin=20)

# ---------------- harness schedule ----------------
main = L.load_pnp("MAIN_BOARD"); synth = L.load_pnp("FREQUENCY_SYNTHESIZER"); power = L.load_pnp("POWER_SUPPLY"); pa = L.load_pnp("RF_PA")
def head_xyz(board, ref):
    pnp = {"MAIN_BOARD": main, "FREQUENCY_SYNTHESIZER": synth, "POWER_SUPPLY": power}[board]
    if ref not in pnp:
        return None
    return L.board_to_head(board, pnp[ref][0], pnp[ref][1])
def pa_xyz(n, ref):
    px, pz = L.pa_positions()[n - 1]
    if ref in pa:
        return (px + pa[ref][0], L.Y_PA, pz + pa[ref][1])
    return (px + 17, L.Y_PA, pz + 30)
def length(a, b, kind):
    if a is None or b is None:
        return None
    d = abs(a[0] - b[0]) + abs(a[1] - b[1]) + abs(a[2] - b[2])
    extra = 40 if kind.startswith("coax") else 60
    return int(math.ceil((d + extra) / 10.0) * 10)
rows = []
# rails Power -> Main / Synth by identical rail net name (from the netlist CSVs)
def conn_nets(board):
    p = os.path.join(ROOT, "engineering", "ELECTRICAL", "netlists", f"{board}_netlist.csv")
    out = {}
    if os.path.isfile(p):
        for r in csv.DictReader(open(p, newline="", encoding="utf-8")):
            if re.match(r"^X\d+$", r["part"]) and r["net"] not in ("GND",):
                out.setdefault(r["part"], set()).add(r["net"])
    return out
pn, mn, sn = conn_nets("POWER_SUPPLY"), conn_nets("MAIN_BOARD"), conn_nets("FREQUENCY_SYNTHESIZER")
cid = 1
for px_ref, nets in sorted(pn.items(), key=lambda kv: int(kv[0][1:])):
    if px_ref == "X1":
        continue
    rail = sorted(nets)[0] if nets else "?"
    dest = None
    for b, cn in (("MAIN_BOARD", mn), ("FREQUENCY_SYNTHESIZER", sn)):
        for ref, ns in cn.items():
            if rail in ns:
                dest = (b, ref); break
        if dest: break
    if dest:
        a, b_ = head_xyz("POWER_SUPPLY", px_ref), head_xyz(dest[0], dest[1])
        rows.append((f"CBL-{cid:03d}", "POWER_SUPPLY", px_ref, dest[0], dest[1], rail, "2-wire 20 AWG, Molex 22-01-2027 both ends", length(a, b_, "wire"), "rail name matched in both netlists"))
    else:
        rows.append((f"CBL-{cid:03d}", "POWER_SUPPLY", px_ref, "?", "?", rail, "2-wire 20 AWG", None, "no connector with this net name on Main/Synth (rail renamed through a filter/inductor or spare output) — resolve with interconnection_table.md"))
    cid += 1
a, b_ = head_xyz("POWER_SUPPLY", "SV1"), head_xyz("MAIN_BOARD", "SV1")
rows.append((f"CBL-{cid:03d}", "POWER_SUPPLY", "SV1", "MAIN_BOARD", "SV1", "enable bus (15 EN + GND)", "20-way 1.27 mm IDC ribbon", length(a, b_, "wire"), "")); cid += 1
for s_ref, m_ref, nm in [("J7", "J1", "100 MHz FPGA sys clk"), ("J5", "J20", "120 MHz DAC"), ("J6", "J18", "120 MHz DAC"), ("J3", "J21", "400 MHz ADC"), ("J10", "J23", "LO TX"), ("J11", "J22", "LO RX"), ("J4", "J19", "test")]:
    rows.append((f"CBL-{cid:03d}", "FREQUENCY_SYNTHESIZER", s_ref, "MAIN_BOARD", m_ref, nm, "coax RG-405 (0.086\") SMA-SMA, phase-stable", length(head_xyz("FREQUENCY_SYNTHESIZER", s_ref), head_xyz("MAIN_BOARD", m_ref), "coax"), "mapping from interconnection_table.md §6")); cid += 1
for s_ref, m_ref in [("JP1", "JP1"), ("JP2", "JP13")]:
    rows.append((f"CBL-{cid:03d}", "FREQUENCY_SYNTHESIZER", s_ref, "MAIN_BOARD", m_ref, "control header", "ribbon/discrete 26 AWG, 2.54 mm housings", length(head_xyz("FREQUENCY_SYNTHESIZER", s_ref), head_xyz("MAIN_BOARD", m_ref), "wire"), "")); cid += 1
vg_map = {1: "X_7", 2: "X_16", 3: "X_8", 4: "X_15", 5: "X_4", 6: "X_11", 7: "X_3", 8: "X_12", 9: "X_5", 10: "X_14", 11: "X_6", 12: "X_13", 13: "X_2", 14: "X_9", 15: "X_1", 16: "X_10"}
rf_pairs = {1: ("J27", "J26"), 2: ("J29", "J28"), 3: ("J25", "J24"), 4: ("J31", "J30"), 5: ("J35", "J34"), 6: ("J37", "J36"), 7: ("J33", "J32"), 8: ("J39", "J38"), 9: ("J47", "J46"), 10: ("J41", "J40"), 11: ("J45", "J44"), 12: ("J43", "J42"), 13: ("J55", "J54"), 14: ("J49", "J48"), 15: ("J53", "J52"), 16: ("J51", "J50")}
sense = ["X3"] + [f"X{38 + i}" for i in range(15)]
for n in range(1, 17):
    rows.append((f"CBL-{cid:03d}", "MAIN_BOARD", vg_map[n], "RF_PA", f"PA{n} X2", f"VG_{n}", "2-wire 24 AWG shielded, Molex 22-01-2027", length(head_xyz("MAIN_BOARD", vg_map[n]), pa_xyz(n, "X2"), "wire"), "PA instance ↔ VG_n assignment PROPOSED (n = n); not documented in CAD")); cid += 1
    rows.append((f"CBL-{cid:03d}", "MAIN_BOARD", sense[n - 1], "RF_PA", f"PA{n} X3", "drain current sense", "3-wire 24 AWG twisted, Molex 22-01-3037", length(head_xyz("MAIN_BOARD", sense[n - 1]), pa_xyz(n, "X3"), "wire"), "Main sense connector ↔ PA n PROPOSED")); cid += 1
    for k, (mref, paref) in enumerate(zip(rf_pairs[n], ("J1", "J2"))):
        rows.append((f"CBL-{cid:03d}", "MAIN_BOARD", mref, "RF_PA", f"PA{n} {paref}", "RF 10.5 GHz" + (" (to PA RFIN)" if paref == "J1" else " (from PA RFOUT)"), "coax RG-405 SMA-SMA, EQUAL LENGTH set", length(head_xyz("MAIN_BOARD", mref), pa_xyz(n, paref), "coax"), "which SMA of the pair is RFIN/RFOUT is UNVERIFIED (interconnection_table §7)")); cid += 1
    rows.append((f"CBL-{cid:03d}", "RF_PA", f"PA{n} J2", "ANTENNA", f"ROW{n}", "RF to antenna row n", "coax RG-405 SMA-2.92 mm, EQUAL LENGTH set", length(pa_xyz(n, "J2"), (L.ANT_POS["x"], L.Y_ANT, L.ANT_POS["z"] + 12 + 4.7 + (n - 1) * 14.3), "coax"), "antenna row n ↔ PA n PROPOSED; equal length mandatory for elevation phase")); cid += 1
    rows.append((f"CBL-{cid:03d}", "DSN-PSU-01", f"OUT{n}", "RF_PA", f"PA{n} 22V", "22 V drain, pulsed", "2-wire 18 AWG twisted, AK300/2 screw terminal", length((W - 70, L.Y_POWER + 10, 260), pa_xyz(n, "22V"), "wire"), "")); cid += 1
rows.append((f"CBL-{cid:03d}", "SLIP RING", "VIN", "POWER_SUPPLY", "X1", "VIN 12-17 V", "2 × 2-wire 16 AWG", length((W / 2, L.Y_POWER - 20, -30), head_xyz("POWER_SUPPLY", "X1"), "wire"), "")); cid += 1
rows.append((f"CBL-{cid:03d}", "SLIP RING", "VIN", "DSN-PSU-01", "IN", "VIN to 22 V boost", "2 × 2-wire 16 AWG", length((W / 2, L.Y_POWER - 20, -30), (W - 70, L.Y_POWER + 10, 260), "wire"), "")); cid += 1
rows.append((f"CBL-{cid:03d}", "SLIP RING", "USB", "MAIN_BOARD", "X53", "USB 2.0 FS to host", "USB 2.0 shielded, mini-B", length((W / 2, L.Y_POWER - 20, -30), head_xyz("MAIN_BOARD", "X53"), "wire"), "")); cid += 1
rows.append((f"CBL-{cid:03d}", "MAIN_BOARD", "stepper pins", "PEDESTAL", "TB6600 (via slip ring)", "STEP/DIR/EN", "3-wire 24 AWG shielded", None, "the driver sits on the fixed base; needs 3 more slip-ring circuits OR move the driver into the head (then only motor phases cross: 4 circuits) — DECISION NEEDED"))
with open(os.path.join(HOUT, "harness_schedule.csv"), "w", newline="", encoding="utf-8") as fh:
    w = csv.writer(fh); w.writerow(["cable_id", "from_board", "from_ref", "to_board", "to_ref", "signal", "cable_type", "length_mm_proposed", "note"]); w.writerows(rows)
md = [f"# Harness schedule — DSN-HAR-01 (PROPOSED DESIGN)\n", f"Rev A · {DATE} · generated by `tools/design_mechanical_drawings.py` from the proposed layout (`tools/design_layout.py`) and the connector positions in the KiCad P&P files. Length = Manhattan distance between connector positions in the head + service allowance (40 mm coax / 60 mm wire), rounded up to 10 mm. Lengths are PROPOSED; cut after a first fit.\n",
      f"Totals: {len(rows)} cables; coax {sum(1 for r in rows if r[6].startswith('coax'))}; wire {sum(1 for r in rows if not r[6].startswith('coax'))}; total proposed length ≈ {sum(r[7] or 0 for r in rows)/1000:.1f} m.\n",
      "| ID | From | To | Signal | Cable | Length (mm) | Note |", "|---|---|---|---|---|---|---|"]
for r in rows:
    md.append(f"| {r[0]} | {r[1]} {r[2]} | {r[3]} {r[4]} | {r[5]} | {r[6]} | {r[7] if r[7] else 'TBD'} | {r[8]} |")
open(os.path.join(HOUT, "HARNESS_SCHEDULE.md"), "w", encoding="utf-8").write("\n".join(md) + "\n")
print("drawings:", sorted(os.listdir(OUT))); print("harness rows:", len(rows), "total m:", round(sum(r[7] or 0 for r in rows) / 1000, 1))
