`timescale 1ns / 1ps
// tb_fft_wrappers.v - xfft_32 and FFT_enhanced (behavioural models) against numpy
// reference vectors (tb/vectors/fft32_*.hex, fft1024_*.hex, generated by tb/gen_vectors.py
// with the same fixed-point model). Tolerance: +/-TOL LSB per component.
// Self-checking: prints "PASS ..." or "FAIL ..." and exits with $finish / $fatal.
module tb_fft_wrappers;
    localparam TOL = 2;
    reg clk = 0;
    reg aresetn = 0;
    always #5 clk = ~clk;

    integer errors = 0;
    integer checked = 0;

    // ---------------- vectors ----------------
    reg [31:0] in32  [0:4*32-1];
    reg [31:0] exp32 [0:4*32-1];
    reg [7:0]  cfg32 [0:3];
    reg [31:0] in1k  [0:2*1024-1];
    reg [31:0] exp1k [0:2*1024-1];
    reg [15:0] cfg1k [0:1];

    // ---------------- DUT: xfft_32 ----------------
    reg  [7:0]  c32_data = 0;  reg c32_valid = 0;
    reg  [31:0] d32_data = 0;  reg d32_valid = 0; reg d32_last = 0;
    wire        c32_ready, d32_ready;
    wire [31:0] o32_data; wire o32_valid, o32_last;
    reg         o32_ready = 1;

    xfft_32 dut32 (
        .aclk(clk), .aresetn(aresetn),
        .s_axis_config_tdata(c32_data), .s_axis_config_tvalid(c32_valid), .s_axis_config_tready(c32_ready),
        .s_axis_data_tdata(d32_data), .s_axis_data_tvalid(d32_valid), .s_axis_data_tready(d32_ready),
        .s_axis_data_tlast(d32_last),
        .m_axis_data_tdata(o32_data), .m_axis_data_tvalid(o32_valid), .m_axis_data_tlast(o32_last),
        .m_axis_data_tready(o32_ready)
    );

    // ---------------- DUT: FFT_enhanced ----------------
    reg  [15:0] c1k_data = 0;  reg c1k_valid = 0;
    reg  [31:0] d1k_data = 0;  reg d1k_valid = 0; reg d1k_last = 0;
    wire        c1k_ready, d1k_ready;
    wire [31:0] o1k_data; wire o1k_valid, o1k_last;

    FFT_enhanced dut1k (
        .aclk(clk), .aresetn(aresetn),
        .s_axis_config_tdata(c1k_data), .s_axis_config_tvalid(c1k_valid), .s_axis_config_tready(c1k_ready),
        .s_axis_data_tdata(d1k_data), .s_axis_data_tvalid(d1k_valid), .s_axis_data_tready(d1k_ready),
        .s_axis_data_tlast(d1k_last),
        .m_axis_data_tdata(o1k_data), .m_axis_data_tvalid(o1k_valid), .m_axis_data_tlast(o1k_last)
    );

    // ---------------- output checkers ----------------
    integer o32_idx = 0, o1k_idx = 0;
    function integer sdiff;
        input [15:0] a; input [15:0] b;
        integer x, y;
        begin
            x = a[15] ? -{16'd0, (~a) + 16'd1} : {16'd0, a};
            y = b[15] ? -{16'd0, (~b) + 16'd1} : {16'd0, b};
            sdiff = (x > y) ? (x - y) : (y - x);
        end
    endfunction

    always @(posedge clk) begin
        if (o32_valid && o32_ready) begin
            if (sdiff(o32_data[15:0], exp32[o32_idx][15:0]) > TOL || sdiff(o32_data[31:16], exp32[o32_idx][31:16]) > TOL) begin
                errors = errors + 1;
                if (errors < 20) $display("FAIL xfft_32 sample %0d: got %h expected %h", o32_idx, o32_data, exp32[o32_idx]);
            end
            if (o32_last !== ((o32_idx % 32) == 31)) begin
                errors = errors + 1; $display("FAIL xfft_32 tlast at sample %0d", o32_idx);
            end
            checked = checked + 1;
            o32_idx = o32_idx + 1;
        end
        if (o1k_valid) begin
            if (sdiff(o1k_data[15:0], exp1k[o1k_idx][15:0]) > TOL || sdiff(o1k_data[31:16], exp1k[o1k_idx][31:16]) > TOL) begin
                errors = errors + 1;
                if (errors < 20) $display("FAIL FFT_enhanced sample %0d: got %h expected %h", o1k_idx, o1k_data, exp1k[o1k_idx]);
            end
            if (o1k_last !== ((o1k_idx % 1024) == 1023)) begin
                errors = errors + 1; $display("FAIL FFT_enhanced tlast at sample %0d", o1k_idx);
            end
            checked = checked + 1;
            o1k_idx = o1k_idx + 1;
        end
    end

    // random back-pressure on the 32-point output (Non-Real-Time throttle)
    always @(posedge clk) o32_ready <= ($random % 4) != 0;

    // ---------------- stimulus ----------------
    integer f, i;
    initial begin
        $readmemh("tb/vectors/fft32_in.hex", in32);
        $readmemh("tb/vectors/fft32_exp.hex", exp32);
        $readmemh("tb/vectors/fft32_cfg.hex", cfg32);
        $readmemh("tb/vectors/fft1024_in.hex", in1k);
        $readmemh("tb/vectors/fft1024_exp.hex", exp1k);
        $readmemh("tb/vectors/fft1024_cfg.hex", cfg1k);
        repeat (5) @(posedge clk);
        aresetn = 1;
        repeat (2) @(posedge clk);

        // 32-point: 4 frames, config before each frame, frames back to back
        for (f = 0; f < 4; f = f + 1) begin
            @(posedge clk); c32_data <= cfg32[f]; c32_valid <= 1;
            @(posedge clk); c32_valid <= 0;
            for (i = 0; i < 32; i = i + 1) begin
                d32_data <= in32[f*32 + i]; d32_valid <= 1; d32_last <= (i == 31);
                @(posedge clk);
                while (!d32_ready) @(posedge clk);
            end
            d32_valid <= 0; d32_last <= 0;
        end

        // 1024-point: forward then inverse
        for (f = 0; f < 2; f = f + 1) begin
            @(posedge clk); c1k_data <= cfg1k[f]; c1k_valid <= 1;
            @(posedge clk); c1k_valid <= 0;
            for (i = 0; i < 1024; i = i + 1) begin
                d1k_data <= in1k[f*1024 + i]; d1k_valid <= 1; d1k_last <= (i == 1023);
                @(posedge clk);
                while (!d1k_ready) @(posedge clk);
            end
            d1k_valid <= 0; d1k_last <= 0;
        end

        // wait for all outputs
        repeat (6000) @(posedge clk);
        if (o32_idx != 128) begin errors = errors + 1; $display("FAIL xfft_32 produced %0d of 128 samples", o32_idx); end
        if (o1k_idx != 2048) begin errors = errors + 1; $display("FAIL FFT_enhanced produced %0d of 2048 samples", o1k_idx); end
        if (errors == 0) begin
            $display("PASS tb_fft_wrappers: %0d samples checked within +/-%0d LSB (xfft_32: 4 frames, FFT_enhanced: fwd+inv)", checked, TOL);
            $finish;
        end else begin
            $display("FAIL tb_fft_wrappers: %0d mismatches", errors);
            $fatal(1);
        end
    end
endmodule
